(function(){
  'use strict';
  const VERSION='0.28.0-dev';
  const ENDPOINT='https://base44.app/api/apps/6aa6b7634a031657377d4fad/functions/telemetryBridge';
  const PAIR_KEY='vectorStaffingCollectorPairing_v1';
  const PENDING_KEY='mvciActionPending_v0280';
  if(window.top!==window.self||window.MVCI_ACTION_RUNNER_0280)return;

  const clean=v=>String(v==null?'':v).replace(/\s+/g,' ').trim();
  const wait=ms=>new Promise(r=>setTimeout(r,ms));
  function loadJson(k,f={}){try{const r=localStorage.getItem(k);return r?JSON.parse(r):f}catch(_){return f}}
  function saveJson(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}}
  function removeKey(k){try{localStorage.removeItem(k)}catch(_){}}
  function pairing(){const p=loadJson(PAIR_KEY,{});return{deviceId:clean(p.deviceId),token:clean(p.token),endpoint:clean(p.endpoint)||ENDPOINT}}
  function parseDate(value){const t=decodeURIComponent(clean(value).replace(/^#/,''));let m=t.match(/\b(20\d{2})[-/](\d{1,2})[-/](\d{1,2})\b/);if(m)return`${m[1]}-${String(+m[2]).padStart(2,'0')}-${String(+m[3]).padStart(2,'0')}`;m=t.match(/\b(\d{1,2})[/-](\d{1,2})[/-](20\d{2})\b/);return m?`${m[3]}-${String(+m[1]).padStart(2,'0')}-${String(+m[2]).padStart(2,'0')}`:''}
  function actualVisibleDate(){const r=window.MVCI_VECTOR_READER_0120;const d=clean(r?.visibleDisplayedDate?.()||'');if(/^\d{4}-\d{2}-\d{2}$/.test(d))return d;const vals=[...document.querySelectorAll('input')].map(x=>parseDate(x.value)).filter(Boolean);const u=[...new Set(vals)];return u.length===1?u[0]:''}
  function isListView(){return /\/Application\/ControlPanel\/ListView/i.test(location.pathname)}
  function listViewUrl(date){const[y,m,d]=date.split('-');return`${location.origin}/Application/ControlPanel/ListView/#${y}/${m}/${d}`}
  async function request(path='',options={}){const p=pairing();if(!p.deviceId||!p.token)throw new Error('Rebel Command pairing is not configured.');const res=await fetch(`${p.endpoint}${path}`,{method:options.method||'GET',cache:'no-store',credentials:'omit',headers:{Authorization:`Bearer ${p.token}`,'X-Rebel-Device-ID':p.deviceId,...(options.body?{'Content-Type':'application/json'}:{})},...(options.body?{body:JSON.stringify(options.body)}:{})});const b=await res.json().catch(()=>({}));if(!res.ok||b?.ok===false)throw new Error(clean(b?.error||`Rebel Command request failed (${res.status})`));return b}
  async function waitForDate(target,timeout=120000){const started=Date.now();let stable=0;while(Date.now()-started<timeout){const d=actualVisibleDate();if(d===target){stable++;if(stable>=3)return true}else stable=0;await wait(document.hidden?1000:300)}return false}
  async function freshGoodCensus(target){if(!await waitForDate(target))throw new Error(`CrewSense did not finish rendering ${target}.`);const bridge=window.MVCI_VECTOR_BRIDGE_0200;if(!bridge?.scrapeNow)throw new Error('Vector staffing collector did not load.');let last='';for(let attempt=1;attempt<=3;attempt++){await wait(attempt===1?700:1500);await bridge.scrapeNow();const s=bridge.status?.()||{};last=s.lastError||s.status||'unknown';if(s.status==='sent-good')return s;if(s.status==='error'&&attempt===3)break;if(s.status==='sent-partial'&&attempt<3)continue;if(s.status==='error'&&attempt<3)continue}throw new Error(`Fresh census did not pass the safety gate (${last}).`)}
  async function preflight(key){const b=await request(`?action=action-preflight&packageKey=${encodeURIComponent(key)}`);return b?.preflight||{}}
  async function preview(pkg){const census=await freshGoodCensus(pkg.targetDate),pf=await preflight(pkg.packageKey);const result=await request('',{method:'POST',body:{version:VERSION,actionPreview:{packageKey:pkg.packageKey,displayedDate:pkg.targetDate,sourceVersion:VERSION,preconditionMatch:pf?.ready===true,evidence:{freshCensusStatus:census.status,lastCapture:census.lastCapture||null,serverPreflight:pf,automatedWriteAttempted:false}}}});if(!result?.actionPreview?.ready)throw new Error(`Input preview blocked: ${result?.actionPreview?.preflight?.reason||pf?.reason||'preconditions changed'}.`);return`READY: ${pkg.summary}. Automated writing remains locked until the approved manual-write proof is complete.`}
  async function verify(pkg){const census=await freshGoodCensus(pkg.targetDate),pf=await preflight(pkg.packageKey),match=pf?.reason==='already_in_target_state';const result=await request('',{method:'POST',body:{version:VERSION,actionVerification:{packageKey:pkg.packageKey,displayedDate:pkg.targetDate,sourceVersion:VERSION,match,evidence:{freshCensusStatus:census.status,lastCapture:census.lastCapture||null,serverPreflight:pf,automatedWriteAttempted:false}}}});if(!result?.actionVerification?.verified)throw new Error('Fresh Vector reread did not match the intended action state.');return`VERIFIED: ${pkg.summary}.`}
  async function worklist(){const b=await request('?action=action-worklist');return Array.isArray(b?.packages)?b.packages:[]}
  function notify(message,kind='info'){try{window.MVCI_COMMAND_CENTER_0280?.notify?.(message,kind)}catch(_){}console[kind==='error'?'error':'info'](`Mission Vector ${VERSION}: ${message}`)}
  async function runPending(){const p=loadJson(PENDING_KEY,{});if(!p.packageKey||!p.targetDate)return;if(Date.now()-Number(p.requestedAt||0)>10*60*1000){removeKey(PENDING_KEY);return}if(!isListView())return;if(!await waitForDate(p.targetDate,120000)){notify(`CrewSense did not finish opening ${p.targetDate} for the pending action.`,'error');return}try{const list=await worklist(),pkg=list.find(x=>x.packageKey===p.packageKey);if(!pkg)throw new Error('The queued action is no longer available.');const msg=pkg.stage==='reread_verification'?await verify(pkg):await preview(pkg);removeKey(PENDING_KEY);notify(msg,'success')}catch(e){removeKey(PENDING_KEY);notify(clean(e?.message||e),'error')}}
  async function startInput(type,date=''){try{const list=await worklist();const matches=list.filter(x=>x.actionType===type&&(!date||x.targetDate===date)).sort((a,b)=>{if(a.stage==='reread_verification'&&b.stage!=='reread_verification')return-1;if(b.stage==='reread_verification'&&a.stage!=='reread_verification')return 1;return String(a.targetDate||'').localeCompare(String(b.targetDate||''))});if(!matches.length)throw new Error(type==='schedule'?'No approved riding-plan changes are waiting.':'No approved OT signups are waiting.');const pkg=matches[0];saveJson(PENDING_KEY,{packageKey:pkg.packageKey,targetDate:pkg.targetDate,requestedAt:Date.now(),type});notify(`${pkg.stage==='reread_verification'?'Verifying':'Preparing'} ${type==='schedule'?'riding-plan change':'OT signup'} for ${pkg.targetDate}…`,'info');if(isListView()&&actualVisibleDate()===pkg.targetDate)runPending();else location.assign(listViewUrl(pkg.targetDate))}catch(e){notify(clean(e?.message||e),'error')}}

  setTimeout(runPending,1200);
  window.addEventListener('hashchange',()=>setTimeout(runPending,700));
  window.MVCI_ACTION_RUNNER_0280={version:VERSION,startInput,runPending,status:()=>({pending:loadJson(PENDING_KEY,{})})};
  window.MVCI_CONTROL_PANEL_0250={...(window.MVCI_CONTROL_PANEL_0250||{}),version:VERSION,startInput};
})();
