(function(){
'use strict';
const VERSION='0.29.0-dev';
const ENDPOINT='https://base44.app/api/apps/6aa6b7634a031657377d4fad/functions/telemetryBridge';
const PAIR_KEY='vectorStaffingCollectorPairing_v1';
const PENDING_KEY='mvciActionPending_v0290';
if(window.top!==window.self||window.MVCI_ACTION_RUNNER_0290)return;
const clean=v=>String(v==null?'':v).replace(/\s+/g,' ').trim();
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function loadJson(k,f={}){try{const r=localStorage.getItem(k);return r?JSON.parse(r):f}catch(_){return f}}
function saveJson(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}}
function removeKey(k){try{localStorage.removeItem(k)}catch(_){}}
function pairing(){const p=loadJson(PAIR_KEY,{});return{deviceId:clean(p.deviceId),token:clean(p.token),endpoint:clean(p.endpoint)||ENDPOINT}}
function actualVisibleDate(){const b=window.MVCI_VECTOR_BRIDGE_0290?.status?.();if(/^\d{4}-\d{2}-\d{2}$/.test(clean(b?.renderedDate)))return clean(b.renderedDate);const r=window.MVCI_VECTOR_READER_0120;const d=clean(r?.visibleDisplayedDate?.()||'');return/^\d{4}-\d{2}-\d{2}$/.test(d)?d:''}
function isListView(){return/\/Application\/ControlPanel\/ListView/i.test(location.pathname)}
function targetHash(date){const[y,m,d]=date.split('-');return`#${y}/${m}/${d}`}
function listViewUrl(date){return`${location.origin}/Application/ControlPanel/ListView/${targetHash(date)}`}
async function request(path='',options={}){const p=pairing();if(!p.deviceId||!p.token)throw new Error('Rebel Command pairing is not configured.');const r=await fetch(`${p.endpoint}${path}`,{method:options.method||'GET',cache:'no-store',credentials:'omit',headers:{Authorization:`Bearer ${p.token}`,'X-Rebel-Device-ID':p.deviceId,...(options.body?{'Content-Type':'application/json'}:{})},...(options.body?{body:JSON.stringify(options.body)}:{})});const b=await r.json().catch(()=>({}));if(!r.ok||b?.ok===false)throw new Error(clean(b?.error||`Rebel Command request failed (${r.status})`));return b}
async function waitForDate(target,timeout=120000){const started=Date.now();let stable=0,last='';while(Date.now()-started<timeout){const d=actualVisibleDate();last=d;if(isListView()&&d===target){stable++;if(stable>=3)return true}else stable=0;await wait(document.hidden?1000:300)}throw new Error(`CrewSense did not finish rendering ${target}${last?` (still showed ${last})`:''}.`)}
async function navigateToDate(target){if(!isListView()){location.assign(listViewUrl(target));return false}if(actualVisibleDate()===target)return true;const h=targetHash(target);if(location.hash===h){location.reload();return false}location.hash=h;await waitForDate(target);return true}
async function freshGoodCensus(target){await waitForDate(target);const bridge=window.MVCI_VECTOR_BRIDGE_0290;if(!bridge?.scrapeNow)throw new Error('Mission Vector staffing collector did not load.');let last='';for(let a=1;a<=3;a++){await wait(a===1?700:1600);const started=Date.now();try{await bridge.scrapeNow({expectedDate:target})}catch(e){last=clean(e?.message||e)}const s=bridge.status?.()||{};last=s.lastError||last||s.status||'unknown';const fresh=s.lastCapture?.date===target&&Date.parse(s.lastCapture?.at||'')>=started-1000;if(s.status==='sent-good'&&fresh)return s;if(a<3)await wait(1200)}throw new Error(`Fresh census for ${target} did not pass the safety gate (${last}).`)}
async function preflight(key){const b=await request(`?action=action-preflight&packageKey=${encodeURIComponent(key)}`);return b?.preflight||{}}
async function preview(pkg){const census=await freshGoodCensus(pkg.targetDate),pf=await preflight(pkg.packageKey);const result=await request('',{method:'POST',body:{version:VERSION,actionPreview:{packageKey:pkg.packageKey,displayedDate:pkg.targetDate,sourceVersion:VERSION,preconditionMatch:pf?.ready===true,evidence:{freshCensusStatus:census.status,lastCapture:census.lastCapture||null,serverPreflight:pf,automatedWriteAttempted:false}}}});if(!result?.actionPreview?.ready)throw new Error(`Input preview blocked: ${result?.actionPreview?.preflight?.reason||pf?.reason||'preconditions changed'}.`);return`READY: ${pkg.summary}. Automated writing remains locked until the approved manual-write proof is complete.`}
async function verify(pkg){const census=await freshGoodCensus(pkg.targetDate),pf=await preflight(pkg.packageKey),match=pf?.reason==='already_in_target_state';const result=await request('',{method:'POST',body:{version:VERSION,actionVerification:{packageKey:pkg.packageKey,displayedDate:pkg.targetDate,sourceVersion:VERSION,match,evidence:{freshCensusStatus:census.status,lastCapture:census.lastCapture||null,serverPreflight:pf,automatedWriteAttempted:false}}}});if(!result?.actionVerification?.verified)throw new Error('Fresh Vector reread did not match the intended action state.');return`VERIFIED: ${pkg.summary}.`}
async function worklist(){const b=await request('?action=action-worklist');return Array.isArray(b?.packages)?b.packages:[]}
function notify(message,kind='info'){try{window.MVCI_COMMAND_CENTER_0290?.notify?.(message,kind)}catch(_){}console[kind==='error'?'error':'info'](`Mission Vector ${VERSION}: ${message}`)}
async function runPending(){const p=loadJson(PENDING_KEY,{});if(!p.packageKey||!p.targetDate)return;if(Date.now()-Number(p.requestedAt||0)>15*60*1000){removeKey(PENDING_KEY);return}try{if(!await navigateToDate(p.targetDate))return;const list=await worklist(),pkg=list.find(x=>x.packageKey===p.packageKey);if(!pkg)throw new Error('The queued action is no longer available.');const msg=pkg.stage==='reread_verification'?await verify(pkg):await preview(pkg);removeKey(PENDING_KEY);notify(msg,'success')}catch(e){removeKey(PENDING_KEY);notify(clean(e?.message||e),'error')}}
async function startInput(type,date=''){try{const list=await worklist();const matches=list.filter(x=>x.actionType===type&&(!date||x.targetDate===date)).sort((a,b)=>{if(a.stage==='reread_verification'&&b.stage!=='reread_verification')return-1;if(b.stage==='reread_verification'&&a.stage!=='reread_verification')return 1;return String(a.targetDate||'').localeCompare(String(b.targetDate||''))});if(!matches.length)throw new Error(type==='schedule'?'No approved riding-plan changes are waiting.':'No approved OT signups are waiting.');const pkg=matches[0];saveJson(PENDING_KEY,{packageKey:pkg.packageKey,targetDate:pkg.targetDate,requestedAt:Date.now(),type});notify(`${pkg.stage==='reread_verification'?'Verifying':'Preparing'} ${type==='schedule'?'riding-plan change':'OT signup'} for ${pkg.targetDate}…`,'info');runPending()}catch(e){notify(clean(e?.message||e),'error')}}
setTimeout(runPending,1600);
window.MVCI_ACTION_RUNNER_0290={version:VERSION,startInput,runPending,status:()=>({pending:loadJson(PENDING_KEY,{})})};
})();