(function(){
'use strict';
const VERSION='0.29.4-dev';
const ROOT_ID='mvci-command-center-v0290';
const TEST_ID='rebel-scout-live-test-0294';
const STATE_KEY='rebelScoutLiveTest0294';
if(window.top!==window.self||window.REBEL_SCOUT_LIVE_TEST_0294)return;
window.REBEL_SCOUT_LIVE_TEST_0294={version:VERSION};
const clean=v=>String(v==null?'':v).replace(/\s+/g,' ').trim();
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const visible=el=>{if(!el||!(el instanceof Element))return false;const s=getComputedStyle(el),r=el.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0};
const all=(sel,root=document)=>{try{return[...root.querySelectorAll(sel)].filter(visible)}catch(_){return[]}};
const text=el=>clean(el?.textContent||'');
function loadState(){try{return JSON.parse(localStorage.getItem(STATE_KEY)||'{}')}catch(_){return{}}}
function saveState(v){try{localStorage.setItem(STATE_KEY,JSON.stringify(v))}catch(_){}}
function notify(msg,kind='info'){window.MVCI_COMMAND_CENTER_0290?.notify?.(msg,kind);console[kind==='error'?'error':'info'](`Rebel Scout ${VERSION}: ${msg}`)}
function actualDate(){const b=window.MVCI_VECTOR_BRIDGE_0290?.status?.();const d=clean(b?.renderedDate||'');if(/^\d{4}-\d{2}-\d{2}$/.test(d))return d;return''}
function targetHash(date){const[y,m,d]=date.split('-');return`#${y}/${m}/${d}`}
async function goDate(date){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error('Choose a valid date.');if(!/\/Application\/ControlPanel\/ListView/i.test(location.pathname)){location.assign(`${location.origin}/Application/ControlPanel/ListView/${targetHash(date)}`);return false}if(actualDate()===date)return true;location.hash=targetHash(date);const start=Date.now();while(Date.now()-start<120000){if(actualDate()===date){await wait(900);return true}await wait(400)}throw new Error(`CrewSense did not finish loading ${date}.`)}
function clickTextExact(label,root=document){const want=clean(label).toLowerCase();const el=all('button,a,[role="button"],span,div,li',root).filter(x=>text(x).toLowerCase()===want).sort((a,b)=>text(a).length-text(b).length)[0];if(!el)return false;(el.closest('button,a,[role="button"]')||el).click();return true}
function findContains(label,root=document){const want=clean(label).toLowerCase();return all('button,a,[role="button"],span,div,li,tr',root).filter(x=>text(x).toLowerCase().includes(want)).sort((a,b)=>text(a).length-text(b).length)[0]||null}
async function waitFor(fn,timeout=12000,label='control'){const start=Date.now();while(Date.now()-start<timeout){const v=fn();if(v)return v;await wait(250)}throw new Error(`Could not find ${label}.`)}
function dialog(){return all('.modal,[role="dialog"],.modal-content,.modal-dialog').sort((a,b)=>text(a).length-text(b).length)[0]||null}
function setSelectOption(select,matcher,required=true){if(!select){if(required)throw new Error('Required CrewSense selector was not found.');return false}const opts=[...select.options],opt=opts.find(o=>matcher(clean(o.textContent||''),String(o.value||'')));if(!opt){if(required)throw new Error('Required CrewSense option was not found.');return false}select.value=opt.value;select.dispatchEvent(new Event('change',{bubbles:true}));select.dispatchEvent(new Event('input',{bubbles:true}));return true}
function selectHaving(pattern,root){return all('select',root).find(s=>[...s.options].some(o=>pattern.test(clean(o.textContent||''))))||null}
async function freshReread(date){try{await window.MVCI_VECTOR_BRIDGE_0290?.scrapeNow?.({expectedDate:date})}catch(_){}}

async function otUnsign(date){if(!await goDate(date))return;const section=await waitFor(()=>findContains('Overtime Sign Up'),'12000','Overtime Sign Up section');const michael=await waitFor(()=>findContains('Michael Brion',section),12000,'Michael Brion OT signup row');if(!confirm(`UNSIGN Michael Brion from overtime on ${date}?\n\nThis WILL change CrewSense.`))return;michael.click();let dlg=await waitFor(()=>dialog(),12000,'OT signup dialog');if(!clickTextExact('Delete user from shift',dlg))throw new Error('Delete user from shift was not found.');await wait(400);dlg=await waitFor(()=>dialog(),12000,'OT delete confirmation');if(!clickTextExact('Do not notify',dlg)&&!clickTextExact('Do Not Notify',dlg))throw new Error('Do not notify confirmation was not found.');await wait(1800);await freshReread(date);notify(`OT UNSIGN submitted for ${date}. CrewSense was reread; verify Michael is absent from Overtime Sign Up.`,'success')}

async function otSignup(date){if(!await goDate(date))return;const section=await waitFor(()=>findContains('Overtime Sign Up'),12000,'Overtime Sign Up section');const existing=findContains('Michael Brion',section);if(existing)throw new Error('Michael Brion already appears in Overtime Sign Up for this date.');const open=await waitFor(()=>findContains('Open slot',section),12000,'OT Open slot');if(!confirm(`SIGN UP Michael Brion for overtime on ${date}?\n\nThis WILL change CrewSense.`))return;open.click();const dlg=await waitFor(()=>dialog(),12000,'OT Add User dialog');const selects=all('select',dlg);let personSet=false,daySet=false;
for(const s of selects){if([...s.options].some(o=>/Michael Brion/i.test(clean(o.textContent)))){setSelectOption(s,t=>/Michael Brion/i.test(t),true);personSet=true}if([...s.options].some(o=>/All day/i.test(clean(o.textContent)))){setSelectOption(s,t=>/All day/i.test(t),true);daySet=true}}
if(!personSet)throw new Error('Michael Brion selector was not found in the OT dialog.');
if(!daySet)console.warn('Rebel Scout: All day selector not present; continuing with CrewSense default.');
if(!clickTextExact('Add User',dlg))throw new Error('Add User button was not found.');await wait(1800);await freshReread(date);notify(`OT SIGN UP submitted for ${date}. CrewSense was reread; verify Michael appears in Overtime Sign Up.`,'success')}

const ROLE_MAP={
  TM:{label:'Tiller',subtype:null,qual:/\[TM\]\s*Tillerman|\bTillerman\b/i,badge:null},
  FFB:{label:'Firefighter',subtype:null,qual:/\[FFB\]\s*Firefighter|\bFirefighter\b/i,badge:null},
  SWING:{label:'FF / Swing',subtype:null,qual:/\[FFB\]\s*Firefighter|\bFirefighter\b/i,badge:/^SWING$/i},
  TADE:{label:'TADE',subtype:/Temporary Fire Engineer/i,qual:/\[DE-A\]\s*Engineer-Aerial|Engineer-Aerial/i,badge:/^TADE$/i},
  TAC:{label:'TAC',subtype:/Temporary Captain/i,qual:/\[Capt\]\s*Captain|\bCaptain\b/i,badge:/^TAC$/i}
};
async function scheduleOne(date,person,roleKey){const role=ROLE_MAP[roleKey];if(!role)throw new Error('Choose a riding role.');if(!person)throw new Error('Choose a person.');if(!await goDate(date))return;
if(!clickTextExact('Edit Assignments'))throw new Error('Edit Assignments button was not found.');await wait(900);
const truck=await waitFor(()=>findContains('Truck 504'),12000,'Truck 504 section');const row=await waitFor(()=>findContains(person,truck),12000,`${person} on Truck 504`);
if(!confirm(`Set ${person} to ${role.label} on ${date}?\n\nThis WILL save a real CrewSense assignment.`))return;row.click();const dlg=await waitFor(()=>dialog(),12000,'assignment editor');
const workType=selectHaving(/Salary Step\s*\[1010\]/i,dlg);if(workType)setSelectOption(workType,t=>/Salary Step\s*\[1010\]/i.test(t),true);
const subtype=selectHaving(/Temporary Fire Engineer|Temporary Captain/i,dlg);if(role.subtype){setSelectOption(subtype,t=>role.subtype.test(t),true)}else if(subtype){const blank=[...subtype.options].find(o=>!clean(o.textContent)||/^(None|Select|--)/i.test(clean(o.textContent)));if(blank){subtype.value=blank.value;subtype.dispatchEvent(new Event('change',{bubbles:true}))}}
const qualifier=selectHaving(/Tillerman|Firefighter|Engineer-Aerial|Captain/i,dlg);setSelectOption(qualifier,t=>role.qual.test(t),true);
const badge=selectHaving(/^SWING$|^TADE$|^TAC$/i,dlg);if(role.badge){setSelectOption(badge,t=>role.badge.test(t),true)}else if(badge){const blank=[...badge.options].find(o=>!clean(o.textContent)||/^(None|Select|--)/i.test(clean(o.textContent)));if(blank){badge.value=blank.value;badge.dispatchEvent(new Event('change',{bubbles:true}))}}
if(!clickTextExact('Save',dlg))throw new Error('Save button was not found in the assignment editor.');await waitFor(()=>/Shift updated successfully/i.test(document.body.innerText||''),15000,'CrewSense save confirmation');await wait(1000);await freshReread(date);notify(`${person} → ${role.label} saved for ${date}. CrewSense was reread.`,'success')}

function ensureUi(){const root=document.getElementById(ROOT_ID);if(!root)return;const body=root.querySelector('.body');if(!body||document.getElementById(TEST_ID))return;const saved=loadState(),wrap=document.createElement('div');wrap.id=TEST_ID;wrap.style.cssText='margin-top:9px;padding-top:9px;border-top:1px solid #c7d1d6;font:11px Arial;color:#334b57';wrap.innerHTML=`<button id="rs-test-toggle" type="button" style="width:100%;min-height:36px;border:1px solid #9a6d31;border-radius:7px;background:#4d3a22;color:#fff;font-weight:800;cursor:pointer">LIVE INPUT TESTS</button><div id="rs-test-body" style="display:none;margin-top:8px"><div style="color:#8a2f2f;font-weight:800;margin-bottom:6px">REAL VECTOR INPUTS — each final action asks for confirmation.</div><label style="display:block;font-weight:700">Test date</label><input id="rs-test-date" type="date" value="${saved.date||'2026-09-22'}" style="width:100%;height:34px;margin:3px 0 7px;border:1px solid #b9c7cd;border-radius:6px;padding:4px 6px;background:white;color:#233"/><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px"><button id="rs-ot-sign" type="button" style="min-height:38px;border:1px solid #16834d;border-radius:7px;background:#179456;color:white;font-weight:800">SIGN UP OT</button><button id="rs-ot-unsign" type="button" style="min-height:38px;border:1px solid #a92e2e;border-radius:7px;background:#bf3737;color:white;font-weight:800">UNSIGN OT</button></div><div style="margin-top:9px;padding-top:8px;border-top:1px dashed #bcc8cd"><label style="display:block;font-weight:700">Truck 504 assignment</label><select id="rs-person" style="width:100%;height:34px;margin:3px 0;border:1px solid #b9c7cd;border-radius:6px;background:white;color:#233"><option value="">Choose person</option><option>Michael Baldree</option><option>Michael Brion</option><option>Jared Weston</option><option>Jerry Weems</option><option>Robert Brooks</option></select><select id="rs-role" style="width:100%;height:34px;margin:3px 0 6px;border:1px solid #b9c7cd;border-radius:6px;background:white;color:#233"><option value="">Choose role</option><option value="TM">Tiller</option><option value="FFB">Firefighter</option><option value="SWING">FF / Swing</option><option value="TADE">TADE</option><option value="TAC">TAC</option></select><button id="rs-schedule-save" type="button" style="width:100%;min-height:38px;border:1px solid #1d6680;border-radius:7px;background:#247995;color:white;font-weight:800">APPLY ONE ASSIGNMENT</button></div><div id="rs-test-status" style="margin-top:7px;color:#627781">Use one change at a time. Rebel Scout stops if it cannot find the exact CrewSense control.</div></div>`;body.appendChild(wrap);
const date=wrap.querySelector('#rs-test-date'),person=wrap.querySelector('#rs-person'),role=wrap.querySelector('#rs-role'),status=wrap.querySelector('#rs-test-status');if(saved.person)person.value=saved.person;if(saved.role)role.value=saved.role;
const persist=()=>saveState({date:date.value,person:person.value,role:role.value});[date,person,role].forEach(x=>x.addEventListener('change',persist));wrap.querySelector('#rs-test-toggle').addEventListener('click',()=>{const x=wrap.querySelector('#rs-test-body');x.style.display=x.style.display==='none'?'block':'none'});
async function run(fn){status.textContent='Working…';try{persist();await fn();status.textContent='Command finished. Verify the CrewSense result before doing another change.'}catch(e){status.textContent=`STOPPED: ${clean(e?.message||e)}`;notify(status.textContent,'error')}}
wrap.querySelector('#rs-ot-sign').addEventListener('click',()=>run(()=>otSignup(date.value)));wrap.querySelector('#rs-ot-unsign').addEventListener('click',()=>run(()=>otUnsign(date.value)));wrap.querySelector('#rs-schedule-save').addEventListener('click',()=>run(()=>scheduleOne(date.value,person.value,role.value)))}
ensureUi();new MutationObserver(ensureUi).observe(document.documentElement,{childList:true,subtree:true});try{document.documentElement.dataset.mvciRuntimeVersion=VERSION}catch(_){}
window.REBEL_SCOUT_LIVE_TEST_0294={version:VERSION,otSignup,otUnsign,scheduleOne};
})();