(function(){
'use strict';
const VERSION='0.29.9-dev';
if(window.top!==window.self||window.REBEL_SCOUT_SLOW_WRITE_0299)return;
window.REBEL_SCOUT_SLOW_WRITE_0299={version:VERSION};
const clean=v=>String(v==null?'':v).replace(/\s+/g,' ').trim();
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const norm=s=>clean(s).toLowerCase();
const longDate=date=>{const[y,m,d]=date.split('-').map(Number);return new Intl.DateTimeFormat('en-US',{weekday:'long',year:'numeric',month:'long',day:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(y,m-1,d)))};
const targetHash=date=>{const[y,m,d]=date.split('-');return`#${y}/${m}/${d}`};
const isSchedule=()=>/\/Application\/ControlPanel\/Schedule/i.test(location.pathname)&&!/ListView/i.test(location.pathname);
function statusText(msg,error=false){const el=document.querySelector('#rs-test-status,#rs296-status');if(el){el.textContent=msg;el.style.color=error?'#b91c1c':'#627781'};try{window.MVCI_COMMAND_CENTER_0290?.notify?.(msg,error?'error':'info')}catch(_){}}
function setVersion(){try{document.documentElement.dataset.mvciRuntimeVersion=VERSION}catch(_){};document.querySelectorAll('*').forEach(el=>{if(el.children.length===0&&/^Rebel Scout\s+0\.29\.\d+-dev$/i.test(clean(el.textContent)))el.textContent=`Rebel Scout ${VERSION}`})}
function diag(msg){try{window.MVCI_SCOUT_DIAGNOSTICS_0297?.sendNow?.(msg)}catch(_){}}
async function waitFor(fn,timeout,label){const start=Date.now();while(Date.now()-start<timeout){try{const v=fn();if(v)return v}catch(_){}await wait(250)}throw new Error(`Timed out waiting for ${label}.`)}
function dateReady(date){if(!isSchedule())return false;const body=clean(document.body?.innerText||'');return body.includes(longDate(date))||location.hash.includes(date)||location.hash.includes(targetHash(date).slice(1));}
async function ensureDate(date){if(!isSchedule()){location.assign(`${location.origin}/Application/ControlPanel/Schedule/${targetHash(date)}`);throw new Error('Crew Scheduler opened for the test date. Wait for it to finish loading, then press APPLY ONE ASSIGNMENT again.');}if(!dateReady(date)){location.hash=targetHash(date);throw new Error('Crew Scheduler is changing dates. Wait for it to finish loading, then press APPLY ONE ASSIGNMENT again.');}statusText('WAITING FOR CREWSENSE TO FINISH LOADING…');await wait(1800);await waitFor(()=>dateReady(date),30000,'Crew Scheduler date');await wait(800)}
function findTruck504(){const nodes=[...document.querySelectorAll('div,section,article,td')];return nodes.filter(el=>/Truck 504/i.test(clean(el.textContent))&&/Michael Baldree|Michael Brion|Jared Weston|Jerry Weems|Robert Brooks/i.test(clean(el.textContent))).sort((a,b)=>clean(a.textContent).length-clean(b.textContent).length)[0]||null}
function findPerson(root,name){return [...root.querySelectorAll('div,span,a,button,li,td')].filter(el=>norm(el.textContent).includes(norm(name))).sort((a,b)=>clean(a.textContent).length-clean(b.textContent).length)[0]||null}
function dialog(){return document.querySelector('#shift-users-dialog')||document.querySelector('.ui-dialog-content#shift-users-dialog')||null}
function wrapper(dlg){return dlg?.closest('.ui-dialog')||dlg}
function selectWithOption(dlg,re){return [...dlg.querySelectorAll('select')].find(s=>[...s.options].some(o=>re.test(clean(o.textContent))))||null}
function selectValues(s){return [...s.options].map(o=>`${clean(o.textContent)}:${o.value}:${o.selected?'1':'0'}`).join('|')}
function isAnimating(el){try{return !!window.jQuery&&window.jQuery(el).is(':animated')}catch(_){return false}}
async function waitModalReady(date,role){statusText('WAITING FOR CREWSENSE ASSIGNMENT WINDOW…');const dlg=await waitFor(()=>dialog(),15000,'assignment editor');const box=wrapper(dlg);const expected=longDate(date);let last='',stable=0;const start=Date.now();while(Date.now()-start<30000){const title=clean(box?.querySelector('.ui-dialog-title')?.textContent||'');const qual=selectWithOption(dlg,/\[TM\]\s*Tillerman|\bTillerman\b/i);const subtype=dlg.querySelector('#work_subtype_id');const labels=selectWithOption(dlg,/^SWING$|^TADE$|^TAC$/i);const sig=[title,qual?selectValues(qual):'',subtype?selectValues(subtype):'',labels?selectValues(labels):''].join('||');const opacity=parseFloat(getComputedStyle(box).opacity||'1');const readyTitle=title.includes(expected);const qualReady=!!qual&&[...qual.options].some(o=>/\[TM\]\s*Tillerman|\bTillerman\b/i.test(clean(o.textContent)));const subtypeReady=!role.subtype||(!!subtype&&[...subtype.options].some(o=>role.subtype.test(clean(o.textContent))));const labelsReady=!role.badge||!!labels;const settled=!isAnimating(box)&&opacity>=0.98;if(sig===last&&readyTitle&&qualReady&&subtypeReady&&labelsReady&&settled)stable++;else stable=0;last=sig;if(stable>=4){await wait(500);diag('modal_ready_0299');return dlg}await wait(300)}throw new Error('CrewSense assignment window never reached a stable ready state. No change was saved.')}
function triggerSelect(select,values){const arr=Array.isArray(values)?values:[values];if(select.multiple){[...select.options].forEach(o=>o.selected=arr.includes(String(o.value)));}else select.value=arr[0]??'';try{if(window.jQuery){window.jQuery(select).val(select.multiple?arr:(arr[0]??'')).trigger('change');}}catch(_){}select.dispatchEvent(new Event('change',{bubbles:true}));select.dispatchEvent(new Event('input',{bubbles:true}));}
function optionValue(select,re){const o=[...select.options].find(o=>re.test(clean(o.textContent)));return o?String(o.value):null}
async function setRoleSelect2(dlg,role){const workType=selectWithOption(dlg,/Salary Step\s*\[1010\]/i);if(workType){const v=optionValue(workType,/Salary Step\s*\[1010\]/i);if(v!=null)triggerSelect(workType,v);await wait(450)}
 const subtype=dlg.querySelector('#work_subtype_id');if(subtype){if(role.subtype){const v=optionValue(subtype,role.subtype);if(v==null)throw new Error('Required Work Subtype is not loaded yet. No change was saved.');triggerSelect(subtype,[v])}else triggerSelect(subtype,[]);await wait(500)}
 const qual=selectWithOption(dlg,/\[TM\]\s*Tillerman|\bTillerman\b/i);if(!qual)throw new Error('CrewSense qualifier source is not ready. No change was saved.');const qv=optionValue(qual,role.qual);if(qv==null)throw new Error('Requested qualifier is not available. No change was saved.');diag('qualifier_before_0299');triggerSelect(qual,[qv]);await wait(700);const selected=[...qual.options].filter(o=>o.selected).map(o=>clean(o.textContent));if(!selected.some(t=>role.qual.test(t)))throw new Error(`CrewSense did not accept ${role.label} qualifier. No change was saved.`);diag('qualifier_after_0299');
 const labels=selectWithOption(dlg,/^SWING$|^TADE$|^TAC$/i);if(labels){if(role.badge){const lv=optionValue(labels,role.badge);if(lv==null)throw new Error('Requested label is not available. No change was saved.');triggerSelect(labels,[lv])}else triggerSelect(labels,[]);await wait(600)}
 return true}
const ROLES={TM:{label:'Tiller',qual:/\[TM\]\s*Tillerman|\bTillerman\b/i,subtype:null,badge:null},FFB:{label:'Firefighter',qual:/\[FFB\]\s*Firefighter|\bFirefighter\b/i,subtype:null,badge:null},SWING:{label:'FF / Swing',qual:/\[FFB\]\s*Firefighter|\bFirefighter\b/i,subtype:null,badge:/^SWING$/i},TADE:{label:'TADE',qual:/\[DE-A\]\s*Engineer-Aerial|Engineer-Aerial/i,subtype:/Temporary Fire Engineer/i,badge:/^TADE$/i},TAC:{label:'TAC',qual:/\[Capt\]\s*Captain|\bCaptain\b/i,subtype:/Temporary Captain/i,badge:/^TAC$/i}};
async function robustSchedule(date,person,roleKey){const role=ROLES[roleKey];if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error('Choose a valid date.');if(!person)throw new Error('Choose a person.');if(!role)throw new Error('Choose a riding role.');await ensureDate(date);const truck=await waitFor(()=>findTruck504(),20000,'Truck 504');const row=await waitFor(()=>findPerson(truck,person),12000,`${person} on Truck 504`);if(!confirm(`Set ${person} to ${role.label} on ${date}?\n\nRebel Scout will WAIT for CrewSense to fully load before changing anything.`))return;statusText('OPENING ASSIGNMENT — WAITING FOR CREWSENSE…');(row.closest('a,button,[role="button"]')||row).click();const dlg=await waitModalReady(date,role);statusText('CREWSENSE READY — SETTING ROLE…');await setRoleSelect2(dlg,role);diag('pre_save_0299');await wait(700);const save=[...dlg.querySelectorAll('button,a,input[type="submit"]')].find(el=>/^save$/i.test(clean(el.textContent||el.value)));if(!save)throw new Error('Save button was not found. No change was saved.');save.click();statusText('SAVING — WAITING FOR CREWSENSE CONFIRMATION…');await waitFor(()=>/Shift updated successfully/i.test(document.body?.innerText||''),20000,'CrewSense save confirmation');await wait(1200);diag('post_save_0299');statusText(`${person} → ${role.label} saved and CrewSense confirmed it.`)}
document.addEventListener('click',ev=>{const btn=ev.target?.closest?.('#rs-schedule-save,#rs296-save');if(!btn)return;ev.preventDefault();ev.stopImmediatePropagation();const box=btn.closest('#rebel-scout-live-test-0294,#rebel-scout-live-test-0296')||document;const date=box.querySelector('input[type="date"]')?.value||'';const person=box.querySelector('select[id*="person"]')?.value||'';const role=box.querySelector('select[id*="role"]')?.value||'';statusText('STARTING SLOW SAFE WRITE…');robustSchedule(date,person,role).catch(e=>{statusText(`STOPPED: ${clean(e?.message||e)}`,true);try{console.error(`Rebel Scout ${VERSION}: STOPPED: ${clean(e?.message||e)}`)}catch(_){}})},true);
setVersion();new MutationObserver(setVersion).observe(document.documentElement,{childList:true,subtree:true});
})();