(function(){
'use strict';
const VERSION='0.29.2-dev';
if(window.top!==window.self||window.REBEL_COMMAND_WRITE_MAPPER_0292)return;
const clean=v=>String(v==null?'':v).replace(/\s+/g,' ').trim();
const visible=el=>{if(!el||!(el instanceof Element))return false;const s=getComputedStyle(el),r=el.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0};
const text=el=>clean(el?.textContent||'');
const all=(sel,root=document)=>{try{return[...root.querySelectorAll(sel)].filter(visible)}catch(_){return[]}};
function bestClickable(el){let n=el;for(let i=0;n&&i<7;i++,n=n.parentElement){if(n.matches?.('button,a,[role="button"],input,select'))return n;if(n.onclick||n.getAttribute?.('ng-click')||n.getAttribute?.('data-toggle'))return n}return el}
function findTextExact(value,root=document){const want=clean(value).toLowerCase();const nodes=all('button,a,[role="button"],label,option,span,div,li,input',root).filter(el=>clean(el.value||text(el)).toLowerCase()===want);return nodes.sort((a,b)=>text(a).length-text(b).length)[0]||null}
function findTextContains(value,root=document){const want=clean(value).toLowerCase();return all('button,a,[role="button"],label,span,div,li',root).filter(el=>text(el).toLowerCase().includes(want)).sort((a,b)=>text(a).length-text(b).length)[0]||null}
function modal(){return all('.modal,[role="dialog"],.modal-dialog,.modal-content').find(el=>/Overtime Sign Up|Truck 504|notify the employee/i.test(text(el)))||all('div').filter(el=>/Overtime Sign Up|Truck 504|notify the employee/i.test(text(el))&&/Save|Add User|Delete user from shift|Notify/i.test(text(el))).sort((a,b)=>text(a).length-text(b).length)[0]||null}
function sectionByHeading(name){const h=findTextContains(name);if(!h)return null;let n=h;for(let i=0;n&&i<8;i++,n=n.parentElement){const t=text(n);if(t.toLowerCase().includes(name.toLowerCase())&&(/Open slot|Michael Brion|Truck 504/i.test(t)))return n}return h.parentElement}
function rowWithin(section,label){if(!section)return null;const want=clean(label).toLowerCase();const candidates=all('div,li,tr,[role="row"],a,button',section).filter(el=>text(el).toLowerCase().includes(want));return candidates.sort((a,b)=>text(a).length-text(b).length)[0]||null}
function selectWithOption(pattern,root=document){return all('select',root).find(s=>[...s.options].some(o=>pattern.test(clean(o.textContent))))||null}
function describeSelect(s){return s?{name:s.name||'',id:s.id||'',value:s.value||'',options:[...s.options].map(o=>clean(o.textContent)).filter(Boolean).slice(0,80)}:null}
function modalSnapshot(){const m=modal();if(!m)return{found:false};return{found:true,title:text(all('h1,h2,h3,h4,.modal-title',m)[0]),buttons:all('button,a,[role="button"]',m).map(text).filter(Boolean),selects:all('select',m).map(describeSelect),inputs:all('input',m).map(x=>({name:x.name||'',id:x.id||'',value:x.value||'',placeholder:x.placeholder||''})),text:text(m).slice(0,2500)}}
function inspectOvertime(){const section=sectionByHeading('Overtime Sign Up');const michael=rowWithin(section,'Michael Brion');const open=rowWithin(section,'Open slot');return{page:/\/Application\/ControlPanel\/Schedule/i.test(location.pathname),sectionFound:!!section,michaelRowFound:!!michael,openSlotFound:!!open,michaelClickable:!!bestClickable(michael),openSlotClickable:!!bestClickable(open),modal:modalSnapshot()}}
function inspectTruck504(person=''){const section=sectionByHeading('Truck 504');const row=person?rowWithin(section,person):null;const m=modal();const subtype=m?selectWithOption(/Temporary Fire Engineer|Temporary Captain/i,m):null;const qualifier=m?selectWithOption(/Tillerman|Firefighter|Engineer-Aerial|Captain/i,m):null;const labels=m?selectWithOption(/^SWING$|^TADE$|^TAC$/i,m):null;return{page:/\/Application\/ControlPanel\/Schedule/i.test(location.pathname),sectionFound:!!section,person:clean(person),personRowFound:!!row,personClickable:!!bestClickable(row),modal:modalSnapshot(),mappedControls:{workSubtype:describeSelect(subtype),qualifier:describeSelect(qualifier),labels:describeSelect(labels)}}}
function mappingFor(position){const p=clean(position).toUpperCase();if(p==='TILLER'||p==='TM')return{workType:'Salary Step [1010]',workSubtype:null,qualifier:'[TM] Tillerman',label:null};if(p==='FIREFIGHTER'||p==='FF'||p==='FFB')return{workType:'Salary Step [1010]',workSubtype:null,qualifier:'[FFB] Firefighter',label:null};if(p==='SWING'||p==='SWING-DESIGNATED'||p==='FF/SWING')return{workType:'Salary Step [1010]',workSubtype:null,qualifier:'[FFB] Firefighter',label:'SWING'};if(p==='TADE')return{workType:'Salary Step [1010]',workSubtype:'Temporary Fire Engineer',qualifier:'[DE-A] Engineer-Aerial',label:'TADE'};if(p==='TAC')return{workType:'Salary Step [1010]',workSubtype:'Temporary Captain',qualifier:'[Capt] Captain',label:'TAC'};return null}
function report(){return{version:VERSION,url:location.href,overtime:inspectOvertime(),truck504:inspectTruck504(),knownMappings:{tillerman:mappingFor('TM'),firefighter:mappingFor('FF'),swingDesignated:mappingFor('SWING'),tade:mappingFor('TADE'),tac:mappingFor('TAC')}}}
function cleanVersionLabels(){for(const host of all('[id^="mvci-"],#mvci-command-center-v0290')){const w=document.createTreeWalker(host,NodeFilter.SHOW_TEXT);let n;while((n=w.nextNode()))if(/0\.29\.[01]-dev/.test(n.nodeValue||''))n.nodeValue=(n.nodeValue||'').replace(/0\.29\.[01]-dev/g,VERSION)}}
cleanVersionLabels();
new MutationObserver(cleanVersionLabels).observe(document.documentElement,{childList:true,subtree:true});
window.REBEL_COMMAND_WRITE_MAPPER_0292={version:VERSION,inspectOvertime,inspectTruck504,mappingFor,modalSnapshot,report};
try{window.dispatchEvent(new CustomEvent('rebel-command-write-mapper-ready',{detail:{version:VERSION}}))}catch(_){ }
})();
