(function(){
'use strict';
const VERSION='0.29.6-dev';
const ROOT_ID='mvci-command-center-v0290';
const OLD_ID='rebel-scout-live-test-0294';
const TEST_ID='rebel-scout-live-test-0296';
const STATE_KEY='rebelScoutLiveTest0296';
if(window.top!==window.self||window.REBEL_SCOUT_LIVE_TEST_0296)return;
window.REBEL_SCOUT_LIVE_TEST_0296={version:VERSION};
const clean=v=>String(v==null?'':v).replace(/\s+/g,' ').trim();
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const visible=el=>{if(!el||!(el instanceof Element))return false;const s=getComputedStyle(el),r=el.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0};
const all=(sel,root=document)=>{try{return[...root.querySelectorAll(sel)].filter(visible)}catch(_){return[]}};
const text=el=>clean(el?.textContent||'');
function loadState(){try{return JSON.parse(localStorage.getItem(STATE_KEY)||localStorage.getItem('rebelScoutLiveTest0294')||'{}')}catch(_){return{}}}
function saveState(v){try{localStorage.setItem(STATE_KEY,JSON.stringify(v))}catch(_){}}
function notify(msg,kind='info'){window.MVCI_COMMAND_CENTER_0290?.notify?.(msg,kind);console[kind==='error'?'error':'info'](`Rebel Scout ${VERSION}: ${msg}`)}
function actualDate(){const b=window.MVCI_VECTOR_BRIDGE_0290?.status?.();const d=clean(b?.renderedDate||'');if(/^\d{4}-\d{2}-\d{2}$/.test(d))return d;const h=location.hash.match(/#(\d{4})-(\d{2})-(\d{2})/);return h?`${h[1]}-${h[2]}-${h[3]}`:''}
function schedulerUrl(date){return`${location.origin}/Application/ControlPanel/Schedule/#${date}`}
function isScheduler(){return/\/Application\/ControlPanel\/Schedule\/?/i.test(location.pathname)}
async function goScheduler(date,pending){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error('Choose a valid date.');saveState({...loadState(),pending});if(!isScheduler()||actualDate()!==date){location.assign(schedulerUrl(date));return false}await wait(800);return true}
function findExact(label,root=document){const want=clean(label).toLowerCase();return all('button,a,[role="button"],span,div,li,tr',root).filter(x=>text(x).toLowerCase()===want).sort((a,b)=>text(a).length-text(b).length)[0]||null}
function findContains(label,root=document){const want=clean(label).toLowerCase();return all('button,a,[role="button"],span,div,li,tr',root).filter(x=>text(x).toLowerCase().includes(want)).sort((a,b)=>text(a).length-text(b).length)[0]||null}
async function waitFor(fn,timeout=15000,label='control'){const start=Date.now();while(Date.now()-start<timeout){const v=fn();if(v)return v;await wait(250)}throw new Error(`Could not find ${label}.`)}
function dialog(){return all('.modal,[role="dialog"],.modal-content,.modal-dialog').sort((a,b)=>text(a).length-text(b).length)[0]||null}
function clickExact(label,root=document){const el=findExact(label,root);if(!el)return false;(el.closest('button,a,[role="button"]')||el).click();return true}
function selectOption(select,regex,required=true){if(!select){if(required)throw new Error('Required CrewSense selector was not found.');return false}const opt=[...select.options].find(o=>regex.test(clean(o.textContent||''))||regex.test(String(o.value||'')));if(!opt){if(required)throw new Error(`Required CrewSense option was not found. Available: ${[...select.options].map(o=>clean(o.textContent)).filter(Boolean).slice(0,20).join(' | ')}`);return false}select.value=opt.value;select.dispatchEvent(new Event('change',{bubbles:true}));select.dispatchEvent(new Event('input',{bubbles:true}));return true}
function fieldContainer(label,root){const lab=all('label,div,span',root).filter(x=>text(x).toUpperCase()===label.toUpperCase()).sort((a,b)=>text(a).length-text(b).length)[0];if(!lab)return null;let p=lab.parentElement;for(let i=0;i<4&&p;i++,p=p.parentElement){if(p.querySelector('select,input')||/QUALIFIERS|LABELS/i.test(text(p)))return p}return lab.parentElement}
async function clearSelected(container,keepRegex=null){if(!container)return;for(const el of all('button,a,span,div',container)){const t=text(el);if(!/[×✕x]$/.test(t)&&t!=='×'&&t!=='✕')continue;const parentText=text(el.parentElement);if(keepRegex&&keepRegex.test(parentText))continue;const target=el.closest('button,a')||el;if(visible(target)){target.click();await wait(180)}}}
async function setMultiChoice(container,desired,fieldName){if(!container)throw new Error(`${fieldName} field was not found.`);const desiredAlready=all('span,div,li',container).some(x=>desired.test(text(x))&&/[×✕]/.test(text(x)));if(desiredAlready)return;
  const selects=all('select',container);for(const s of selects){if([...s.options].some(o=>desired.test(clean(o.textContent||'')))){selectOption(s,desired,true);await wait(300);return}}
  const select=selects[0];if(select){try{select.focus();select.click()}catch(_){}await wait(250)}
  const opt=all('option,li,[role="option"],a,div,span',document).filter(x=>desired.test(text(x))).sort((a,b)=>text(a).length-text(b).length)[0];
  if(opt){(opt.closest('li,[role="option"],a,button')||opt).click();await wait(300);return}
  throw new Error(`${fieldName} option was not found. Visible field text: ${text(container).slice(0,240)}`)
}
async function freshReread(date){try{await window.MVCI_VECTOR_BRIDGE_0290?.scrapeNow?.({expectedDate:date})}catch(_){}}
async function otUnsign(date){if(!await goScheduler(date,{type:'otUnsign',date}))return;const section=await waitFor(()=>findContains('Overtime Sign Up'),15000,'Overtime Sign Up section');const michael=await waitFor(()=>findContains('Michael Brion',section),12000,'Michael Brion OT signup row');if(!confirm(`UNSIGN Michael Brion from overtime on ${date}?\n\nThis WILL change CrewSense.`))return;michael.click();let dlg=await waitFor(()=>dialog(),12000,'OT signup dialog');if(!clickExact('Delete user from shift',dlg))throw new Error('Delete user from shift was not found.');await wait(400);dlg=await waitFor(()=>dialog(),12000,'OT delete confirmation');if(!clickExact('Do not notify',dlg)&&!clickExact('Do Not Notify',dlg))throw new Error('Do not notify confirmation was not found.');await wait(1800);await freshReread(date);notify(`OT UNSIGN submitted for ${date}. Verify Michael is absent from Overtime Sign Up.`,'success')}
async function otSignup(date){if(!await goScheduler(date,{type:'otSignup',date}))return;const section=await waitFor(()=>findContains('Overtime Sign Up'),15000,'Overtime Sign Up section');if(findContains('Michael Brion',section))throw new Error('Michael Brion already appears in Overtime Sign Up for this date.');const open=await waitFor(()=>findContains('Open slot',section),12000,'OT Open slot');if(!confirm(`SIGN UP Michael Brion for overtime on ${date}?\n\nThis WILL change CrewSense.`))return;open.click();const dlg=await waitFor(()=>dialog(),12000,'OT Add User dialog');const selects=all('select',dlg);let personSet=false;for(const s of selects){if([...s.options].some(o=>/Michael Brion/i.test(clean(o.textContent)))){selectOption(s,/Michael Brion/i,true);personSet=true}}if(!personSet)throw new Error('Michael Brion selector was not found in the OT dialog.');if(!clickExact('Add User',dlg))throw new Error('Add User button was not found.');await wait(1800);await freshReread(date);notify(`OT SIGN UP submitted for ${date}. Verify Michael appears in Overtime Sign Up.`,'success')}
const ROLE_MAP={
 TM:{label:'Tiller',subtype:null,qual:/\[?TM\]?|Tillerman|\bTiller\b/i,badge:null},
 FFB:{label:'Firefighter',subtype:null,qual:/\[?FFB\]?|Firefighter/i,badge:null},
 SWING:{label:'FF / Swing',subtype:null,qual:/\[?FFB\]?|Firefighter/i,badge:/^SWING$/i},
 TADE:{label:'TADE',subtype:/Temporary Fire Engineer/i,qual:/\[?DE-A\]?|Engineer-Aerial/i,badge:/^TADE$/i},
 TAC:{label:'TAC',subtype:/Temporary Captain/i,qual:/\[?Capt\]?|Captain/i,badge:/^TAC$/i}
};
async function scheduleOne(date,person,roleKey){const role=ROLE_MAP[roleKey];if(!role)throw new Error('Choose a riding role.');if(!person)throw new Error('Choose a person.');if(!await goScheduler(date,{type:'scheduleOne',date,person,roleKey}))return;
 const truck=await waitFor(()=>findContains('Truck 504'),15000,'Truck 504 section');const row=await waitFor(()=>findContains(person,truck),12000,`${person} on Truck 504`);
 if(!confirm(`Set ${person} to ${role.label} on ${date}?\n\nThis WILL save a real CrewSense assignment.`))return;row.click();const dlg=await waitFor(()=>dialog(),12000,'Truck 504 assignment editor');
 const workType=all('select',dlg).find(s=>[...s.options].some(o=>/Salary Step\s*\[1010\]/i.test(clean(o.textContent))));if(workType)selectOption(workType,/Salary Step\s*\[1010\]/i,true);
 const subtypeContainer=fieldContainer('WORK SUBTYPE',dlg);if(role.subtype){let subtype=all('select',subtypeContainer||dlg).find(s=>[...s.options].some(o=>role.subtype.test(clean(o.textContent))));if(subtype)selectOption(subtype,role.subtype,true);else{const input=all('input',subtypeContainer||dlg)[0];if(input){input.click();await wait(250);const opt=all('li,[role="option"],div,span',document).find(x=>role.subtype.test(text(x)));if(!opt)throw new Error('Required Work Subtype option was not found.');opt.click()}else throw new Error('Work Subtype control was not found.')}}else if(subtypeContainer){await clearSelected(subtypeContainer)}
 const qualContainer=fieldContainer('QUALIFIERS',dlg);await clearSelected(qualContainer);await wait(250);await setMultiChoice(qualContainer,role.qual,'Qualifier');
 const labelContainer=fieldContainer('LABELS',dlg);await clearSelected(labelContainer);await wait(200);if(role.badge)await setMultiChoice(labelContainer,role.badge,'Label');
 if(!clickExact('Save',dlg))throw new Error('Save button was not found in the assignment editor.');await waitFor(()=>/Shift updated successfully/i.test(document.body.innerText||''),15000,'CrewSense save confirmation');await wait(900);await freshReread(date);notify(`${person} → ${role.label} saved for ${date}. CrewSense was reread.`,'success')}
function ensureUi(){document.getElementById(OLD_ID)?.remove();const root=document.getElementById(ROOT_ID);if(!root)return;const body=root.querySelector('.body');if(!body||document.getElementById(TEST_ID))return;const saved=loadState(),wrap=document.createElement('div');wrap.id=TEST_ID;wrap.style.cssText='margin-top:9px;padding-top:9px;border-top:1px solid #c7d1d6;font:11px Arial;color:#334b57';wrap.innerHTML=`<button id="rs296-toggle" type="button" style="width:100%;min-height:36px;border:1px solid #9a6d31;border-radius:7px;background:#4d3a22;color:#fff;font-weight:800">LIVE INPUT TESTS</button><div id="rs296-body" style="display:none;margin-top:8px"><div style="color:#8a2f2f;font-weight:800;margin-bottom:6px">REAL VECTOR INPUTS — Crew Scheduler only. Each final action asks for confirmation.</div><label style="display:block;font-weight:700">Test date</label><input id="rs296-date" type="date" value="${saved.date||'2026-09-22'}" style="width:100%;height:34px;margin:3px 0 7px;border:1px solid #b9c7cd;border-radius:6px;padding:4px 6px;background:white;color:#233"/><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px"><button id="rs296-sign" type="button" style="min-height:38px;border:1px solid #16834d;border-radius:7px;background:#179456;color:white;font-weight:800">SIGN UP OT</button><button id="rs296-unsign" type="button" style="min-height:38px;border:1px solid #a92e2e;border-radius:7px;background:#bf3737;color:white;font-weight:800">UNSIGN OT</button></div><div style="margin-top:9px;padding-top:8px;border-top:1px dashed #bcc8cd"><label style="display:block;font-weight:700">Truck 504 assignment</label><select id="rs296-person" style="width:100%;height:34px;margin:3px 0;border:1px solid #b9c7cd;border-radius:6px;background:white;color:#233"><option value="">Choose person</option><option>Michael Baldree</option><option>Michael Brion</option><option>Jared Weston</option><option>Jerry Weems</option><option>Robert Brooks</option></select><select id="rs296-role" style="width:100%;height:34px;margin:3px 0 6px;border:1px solid #b9c7cd;border-radius:6px;background:white;color:#233"><option value="">Choose role</option><option value="TM">Tiller</option><option value="FFB">Firefighter</option><option value="SWING">FF / Swing</option><option value="TADE">TADE</option><option value="TAC">TAC</option></select><button id="rs296-save" type="button" style="width:100%;min-height:38px;border:1px solid #1d6680;border-radius:7px;background:#247995;color:white;font-weight:800">APPLY ONE ASSIGNMENT</button></div><div id="rs296-status" style="margin-top:7px;color:#627781">0.29.6 removes the current qualifier/label first, then adds the requested one.</div></div>`;body.appendChild(wrap);
 const date=wrap.querySelector('#rs296-date'),person=wrap.querySelector('#rs296-person'),role=wrap.querySelector('#rs296-role'),status=wrap.querySelector('#rs296-status');if(saved.person)person.value=saved.person;if(saved.role)role.value=saved.role;const persist=()=>saveState({date:date.value,person:person.value,role:role.value});[date,person,role].forEach(x=>x.addEventListener('change',persist));wrap.querySelector('#rs296-toggle').addEventListener('click',()=>{const x=wrap.querySelector('#rs296-body');x.style.display=x.style.display==='none'?'block':'none'});async function run(fn){status.textContent='Working…';try{persist();await fn();saveState({...loadState(),pending:null});status.textContent='Command finished. Verify CrewSense before doing another change.'}catch(e){saveState({...loadState(),pending:null});status.textContent=`STOPPED: ${clean(e?.message||e)}`;notify(status.textContent,'error')}}wrap.querySelector('#rs296-sign').addEventListener('click',()=>run(()=>otSignup(date.value)));wrap.querySelector('#rs296-unsign').addEventListener('click',()=>run(()=>otUnsign(date.value)));wrap.querySelector('#rs296-save').addEventListener('click',()=>run(()=>scheduleOne(date.value,person.value,role.value)))}
function resume(){const s=loadState(),p=s.pending;if(!p||!isScheduler())return;setTimeout(()=>{if(p.type==='otSignup')otSignup(p.date).catch(e=>notify(`STOPPED: ${clean(e?.message||e)}`,'error'));if(p.type==='otUnsign')otUnsign(p.date).catch(e=>notify(`STOPPED: ${clean(e?.message||e)}`,'error'));if(p.type==='scheduleOne')scheduleOne(p.date,p.person,p.roleKey).catch(e=>notify(`STOPPED: ${clean(e?.message||e)}`,'error'))},1400)}
ensureUi();new MutationObserver(ensureUi).observe(document.documentElement,{childList:true,subtree:true});resume();try{document.documentElement.dataset.mvciRuntimeVersion=VERSION}catch(_){}
window.REBEL_SCOUT_LIVE_TEST_0296={version:VERSION,otSignup,otUnsign,scheduleOne};
})();