(function(){
'use strict';
const VERSION='0.30.0-dev';
const ROOT_ID='mvci-command-center-v0290';
const PANEL_ID='rebel-scout-assisted-v0300';
const ENDPOINT='https://base44.app/api/apps/6aa6b7634a031657377d4fad/functions/telemetryBridge';
const PAIR_KEY='vectorStaffingCollectorPairing_v1';
const LOCK_KEY='mvciDataSyncOwner_v0290';
const LOCK_OWNER='rebel-scout-assisted-v0300';
const STATE_KEY='rebelScoutAssistedState_v0300';
const TRACE_KEY='rebelScoutHumanTrace_v0300';
const TRACE_MAX_AGE=10*60*1000;
const TRACE_PATCH='2026-09-16-trace-only';
const PREPARATION_ENABLED=false; // No field preparation or Save authorization in trace-only mode.
if(window.top!==window.self||window.REBEL_SCOUT_ASSISTED_0300)return;
window.REBEL_SCOUT_ASSISTED_0300={version:VERSION};
const clean=v=>String(v==null?'':v).replace(/\s+/g,' ').trim();
const clip=(v,n=1200)=>clean(v).slice(0,n);
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isoDate=/^\d{4}-\d{2}-\d{2}$/;
function loadJson(key,f={}){try{const x=localStorage.getItem(key);return x?JSON.parse(x):f}catch(_){return f}}
function saveJson(key,v){try{localStorage.setItem(key,JSON.stringify(v))}catch(_){}}
function removeKey(key){try{localStorage.removeItem(key)}catch(_){}}
function pairing(){const p=loadJson(PAIR_KEY,{});return{deviceId:clean(p.deviceId),token:clean(p.token),endpoint:clean(p.endpoint)||ENDPOINT}}
function state(){return loadJson(STATE_KEY,{date:'2026-09-23',person:'Jerry Weems',role:'TM',armed:false})}
function saveState(v){saveJson(STATE_KEY,{...state(),...v})}
function isSchedule(){return /\/Application\/ControlPanel\/Schedule/i.test(location.pathname)&&!/ListView/i.test(location.pathname)}
function isLogin(){return /\/login|\/signin/i.test(location.pathname)||/\blog\s*in\b|\bsign\s*in\b/i.test(clip(document.title,200))&& !/Crew Scheduler/i.test(document.title)}
function targetHash(date){if(!isoDate.test(date||''))throw new Error('Invalid ISO date.');const d=new Date(`${date}T12:00:00Z`);if(Number.isNaN(d.getTime())||d.toISOString().slice(0,10)!==date)throw new Error('Invalid calendar date.');return`#${date}`}
function scheduleUrl(date){return`${location.origin}/Application/ControlPanel/Schedule/${targetHash(date)}`}
function longDate(date){const[y,m,d]=date.split('-').map(Number);return new Intl.DateTimeFormat('en-US',{weekday:'long',year:'numeric',month:'long',day:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(y,m-1,d)))}
function renderedDate(){const title=document.querySelector('#ui-dialog-title-shift-users-dialog')?.textContent||'';const dm=title.match(/(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday),\s+([A-Za-z]+)\s+(\d{1,2}),\s+(\d{4})/i);if(dm){const d=new Date(`${dm[2]} ${dm[3]}, ${dm[4]} 12:00:00`);if(!Number.isNaN(d.getTime()))return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};const body=clip(document.body?.innerText||'',9000);const m=body.match(/(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday),\s+([A-Za-z]{3,9})\s+(\d{1,2}),?\s+(\d{4})/i);if(m){const d=new Date(`${m[2]} ${m[3]}, ${m[4]} 12:00:00`);if(!Number.isNaN(d.getTime()))return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};return''}
function setStatus(msg,kind='info'){const el=document.querySelector('#rs0300-status');if(el){el.textContent=msg;el.style.color=kind==='error'?'#9b1c1c':kind==='success'?'#17643a':'#526a76'};try{window.MVCI_COMMAND_CENTER_0290?.notify?.(msg,kind)}catch(_){};console[kind==='error'?'error':'info'](`Rebel Scout ${VERSION}: ${msg}`)}
function runtimeMeta(){return{loaderVersion:clean(document.documentElement.dataset.mvciLoaderVersion||''),manifestRuntime:clean(window.__mvciLiveLoader?.runtimeVersion||document.documentElement.dataset.mvciRuntimeVersion||''),moduleVersion:VERSION}}
function nodeSummary(el){if(!(el instanceof Element))return null;const attrs={};for(const a of [...el.attributes||[]]){if(a.name.startsWith('data-')||['id','class','role','href','onclick','aria-expanded','aria-controls'].includes(a.name))attrs[a.name]=clip(a.value,300)}return{tag:el.tagName.toLowerCase(),text:clip(el.textContent||'',250),attrs}}
function pathSummary(path){return(path||[]).filter(x=>x instanceof Element).slice(0,14).map(nodeSummary).filter(Boolean)}
function jQueryHandlers(path){try{const jq=window.jQuery;if(!jq||!jq._data)return[];return(path||[]).filter(x=>x instanceof Element).slice(0,10).map((el,i)=>{const events=jq._data(el,'events')||{};return{pathIndex:i,node:nodeSummary(el),events:Object.keys(events).reduce((o,k)=>{o[k]=(events[k]||[]).map(h=>({namespace:h.namespace||'',selector:h.selector||'',handler:clip(h.handler?.toString?.()||'',500)}));return o},{})}}).filter(x=>Object.keys(x.events).length)}catch(_){return[]}}
let pendingNet=0,lastMutationAt=Date.now(),netLog=[];
new MutationObserver(()=>{lastMutationAt=Date.now()}).observe(document.documentElement,{childList:true,subtree:true,attributes:true,characterData:false});
function installPageProbe(){if(document.getElementById('mvci-page-probe-v0300'))return;const s=document.createElement('script');s.id='mvci-page-probe-v0300';s.textContent=`(()=>{if(window.__MVCI_PAGE_PROBE_0300)return;window.__MVCI_PAGE_PROBE_0300=1;const fire=d=>document.dispatchEvent(new CustomEvent('mvci:page-net',{detail:d}));const O=XMLHttpRequest.prototype.open,S=XMLHttpRequest.prototype.send;XMLHttpRequest.prototype.open=function(m,u,...a){this.__mvci={m:String(m||'GET'),u:String(u||''),t:0};return O.call(this,m,u,...a)};XMLHttpRequest.prototype.send=function(...a){const x=this.__mvci||{m:'GET',u:'',t:0};x.t=Date.now();fire({phase:'start',kind:'xhr',m:x.m,u:x.u,t:x.t});this.addEventListener('loadend',()=>fire({phase:'end',kind:'xhr',m:x.m,u:x.u,status:this.status,t:Date.now(),ms:Date.now()-x.t}),{once:true});return S.apply(this,a)};const F=window.fetch;if(F)window.fetch=async function(input,init){const u=typeof input==='string'?input:(input&&input.url)||'',m=(init&&init.method)||(input&&input.method)||'GET',t=Date.now();fire({phase:'start',kind:'fetch',m:String(m),u:String(u),t});try{const r=await F.apply(this,arguments);fire({phase:'end',kind:'fetch',m:String(m),u:String(u),status:r.status,t:Date.now(),ms:Date.now()-t});return r}catch(e){fire({phase:'end',kind:'fetch',m:String(m),u:String(u),status:0,t:Date.now(),ms:Date.now()-t,error:String(e&&e.message||e)});throw e}};document.addEventListener('mvci:page-select',ev=>{const d=ev.detail||{},sel=document.querySelector(d.selector);let ok=false,err='';try{if(!sel)throw new Error('select not found');const jq=window.jQuery;if(!jq)throw new Error('page jQuery unavailable');const vals=Array.isArray(d.values)?d.values:[d.values];jq(sel).val(sel.multiple?vals:(vals[0]??'')).trigger('change');ok=true}catch(e){err=String(e&&e.message||e)}document.dispatchEvent(new CustomEvent('mvci:page-select-result',{detail:{nonce:d.nonce,ok,err,value:sel?Array.from(sel.selectedOptions||[]).map(o=>o.value):[]}}))});})();`;document.documentElement.appendChild(s)}
installPageProbe();
document.addEventListener('mvci:page-net',ev=>{const d=ev.detail||{};if(d.phase==='start')pendingNet++;if(d.phase==='end')pendingNet=Math.max(0,pendingNet-1);netLog.push({...d,u:clip(d.u,400)});if(netLog.length>50)netLog=netLog.slice(-50)});
async function diagnostic(kind,stage,message,extra={}){const p=pairing();if(!p.deviceId||!p.token)return false;const st=state(),trace=loadJson(TRACE_KEY,{});const dlg=document.querySelector('#shift-users-dialog'),form=dlg?.querySelector('#shift-user-form');const selects=dlg?[...dlg.querySelectorAll('select')].map(s=>({id:s.id,name:s.name,multiple:!!s.multiple,value:s.value,selected:[...s.selectedOptions].map(o=>({value:o.value,text:clip(o.textContent,160)})),options:[...s.options].slice(0,80).map(o=>({value:o.value,text:clip(o.textContent,160),selected:o.selected}))})):[];const snap={...runtimeMeta(),page:{url:location.href,path:location.pathname,hash:location.hash,title:document.title,renderedDate:renderedDate(),isSchedule:isSchedule(),isLogin:isLogin()},network:{pending:pendingNet,last:netLog.slice(-20)},lock:loadJson(LOCK_KEY,{}),trace:{armed:!!st.armed,last:trace&&trace.at?trace:null},modal:dlg?{title:clip(document.querySelector('#ui-dialog-title-shift-users-dialog')?.textContent||'',500),opacity:clip(getComputedStyle(dlg.closest('.ui-dialog')||dlg).opacity||'',50),html:clip((dlg.closest('.ui-dialog')||dlg).outerHTML,16000),form:{shiftId:form?.querySelector('input[name="shift_id"]')?.value||'',date:form?.querySelector('input[name="date"]')?.value||'',shiftUsersId:form?.querySelector('input[name="shift_users_id"]')?.value||''},selects}:null,...extra};const payload={version:VERSION,scoutDiagnostic:{diagnosticId:`scoutdiag:${p.deviceId}:${Date.now()}:${Math.random().toString(36).slice(2,8)}`,runtimeVersion:VERSION,kind,actionType:'assisted_schedule',targetDate:st.date||renderedDate()||'',personName:st.person||'',requestedRole:st.role||'',message:clip(message,1500),pageUrl:location.href,pagePath:location.pathname,pageHash:location.hash,renderedDate:renderedDate(),stage,occurredAt:new Date().toISOString(),snapshot:snap}};try{const r=await fetch(p.endpoint||ENDPOINT,{method:'POST',cache:'no-store',credentials:'omit',headers:{Authorization:`Bearer ${p.token}`,'X-Rebel-Device-ID':p.deviceId,'Content-Type':'application/json'},body:JSON.stringify(payload)});return r.ok}catch(_){return false}}
function acquireLock(){try{window.MVCI_COMMAND_CENTER_0290?.stopSync?.('Data sync paused for Rebel Scout assisted input.')}catch(_){};saveJson(LOCK_KEY,{tabId:LOCK_OWNER,heartbeat:Date.now(),mode:'assisted_input',expiresAt:Date.now()+15*60*1000});document.documentElement.dataset.mvciAssistedInputLock='1'}
function pulseLock(){const x=loadJson(LOCK_KEY,{});if(x.tabId===LOCK_OWNER)saveJson(LOCK_KEY,{...x,heartbeat:Date.now(),expiresAt:Date.now()+15*60*1000})}
function releaseLock(){const x=loadJson(LOCK_KEY,{});if(x.tabId===LOCK_OWNER)removeKey(LOCK_KEY);delete document.documentElement.dataset.mvciAssistedInputLock}
setInterval(()=>{if(document.documentElement.dataset.mvciAssistedInputLock==='1')pulseLock()},30000);
async function waitQuiescent(timeout=20000){const start=Date.now();while(Date.now()-start<timeout){if(isLogin())throw new Error('CrewSense session is not authenticated. Assisted input aborted.');if(pendingNet===0&&Date.now()-lastMutationAt>=650)return true;await wait(150)}throw new Error('CrewSense did not become quiet. No field was changed.')}
function exactModal(){const dlg=document.querySelector('#shift-users-dialog');if(!dlg||!dlg.isConnected)return null;const form=dlg.querySelector('#shift-user-form');if(!form)return null;return{dlg,form,box:dlg.closest('.ui-dialog')||dlg}}
function expectedModal(date){const m=exactModal();if(!m)throw new Error('Open the person assignment manually in CrewSense first. Scout will not guess which row to click.');const title=clean(document.querySelector('#ui-dialog-title-shift-users-dialog')?.textContent||'');if(!/Truck\s*504/i.test(title))throw new Error('The open assignment is not Truck 504. Nothing changed.');const fd=m.form.querySelector('input[name="date"]')?.value||'';if(fd!==date)throw new Error(`The open assignment is for ${fd||'an unknown date'}, not ${date}. Nothing changed.`);return m}
function optionByValueOrText(select,value,re){return[...select.options].find(o=>String(o.value)===String(value))||[...select.options].find(o=>re?.test(clean(o.textContent||'')))||null}
function selectedTexts(select){return[...select.selectedOptions].map(o=>clean(o.textContent||''))}
function cssEscape(v){if(window.CSS?.escape)return CSS.escape(v);return String(v).replace(/[^a-zA-Z0-9_-]/g,c=>`\\${c}`)}
async function pageSetSelect(select,values){const selector=select.id?`#${cssEscape(select.id)}`:select.name?`select[name="${String(select.name).replace(/"/g,'\\"')}"]`:'';if(!selector)throw new Error('CrewSense select has no stable id/name. Nothing changed.');const nonce=`sel-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;return await new Promise((resolve,reject)=>{let done=false;const handler=ev=>{if(ev.detail?.nonce!==nonce)return;done=true;document.removeEventListener('mvci:page-select-result',handler);ev.detail?.ok?resolve(ev.detail):reject(new Error(ev.detail?.err||'CrewSense page-context selection failed.'))};document.addEventListener('mvci:page-select-result',handler);document.dispatchEvent(new CustomEvent('mvci:page-select',{detail:{nonce,selector,values}}));setTimeout(()=>{if(!done){document.removeEventListener('mvci:page-select-result',handler);reject(new Error('CrewSense page-context selection timed out.'))}},5000)})}
const ROLES={
 TM:{label:'Tiller',workType:'33965',subtype:[],qualText:/\[TM\]\s*Tillerman|\bTillerman\b/i,badge:[]},
 FFB:{label:'Firefighter',workType:'33965',subtype:[],qualText:/\[FFB\]\s*Firefighter|\bFirefighter\b/i,badge:[]},
 SWING:{label:'FF / Swing',workType:'33965',subtype:[],qualText:/\[FFB\]\s*Firefighter|\bFirefighter\b/i,badgeText:/^SWING$/i},
 TADE:{label:'TADE',workType:'33965',subtype:['25864'],qualText:/\[DE-A\]\s*Engineer-Aerial|Engineer-Aerial/i,badgeText:/^TADE$/i},
 TAC:{label:'TAC',workType:'33965',subtype:['25870'],qualText:/\[Capt\]\s*Captain|\bCaptain\b/i,badgeText:/^TAC$/i}
};
async function stableOptions(select,timeout=15000){let last='',stable=0,start=Date.now();while(Date.now()-start<timeout){if(!select.isConnected)throw new Error('CrewSense replaced the assignment field while loading. Nothing changed.');const sig=[...select.options].map(o=>`${o.value}:${clean(o.textContent||'')}`).join('|');if(sig&&sig===last)stable++;else stable=0;last=sig;if(stable>=3&&pendingNet===0)return true;await wait(250)}throw new Error(`CrewSense options for ${select.id||select.name||'field'} did not stabilize. Nothing changed.`)}
function findQualSelect(dlg){const rows=[...dlg.querySelectorAll('select')];const hits=rows.filter(s=>[...s.options].some(o=>/\[TM\]\s*Tillerman|\[FFB\]\s*Firefighter|\[DE-A\]\s*Engineer-Aerial|\[Capt\]\s*Captain/i.test(clean(o.textContent||''))));if(hits.length!==1)throw new Error(`Expected exactly one qualifier source; found ${hits.length}. Nothing changed.`);return hits[0]}
function findLabelSelect(dlg){const rows=[...dlg.querySelectorAll('select')];const hits=rows.filter(s=>[...s.options].some(o=>/^SWING$|^TADE$|^TAC$/i.test(clean(o.textContent||''))));if(hits.length!==1)throw new Error(`Expected exactly one label source; found ${hits.length}. Nothing changed.`);return hits[0]}
async function verifyRendered(select,expectedTexts){await waitQuiescent(15000);const selected=selectedTexts(select);for(const re of expectedTexts){if(!selected.some(t=>re.test(t)))throw new Error(`CrewSense did not retain expected selection ${re}. Nothing was saved.`)}const c=select.nextElementSibling?.querySelector?.('.select2-selection__rendered')||select.parentElement?.querySelector?.('.select2-selection__rendered');if(c){const txt=clean(c.textContent||'');for(const re of expectedTexts){if(!re.test(txt))throw new Error(`CrewSense Select2 display did not confirm ${re}. Nothing was saved.`)}}}
async function prepareOpenAssignment(){if(!PREPARATION_ENABLED)throw new Error('TRACE-ONLY MODE: field preparation is disabled. Do not Save.');const st=state(),role=ROLES[st.role];if(!isoDate.test(st.date||''))throw new Error('Choose a valid date.');if(!st.person)throw new Error('Choose a person.');if(!role)throw new Error('Choose a role.');if(isLogin())throw new Error('CrewSense session is not authenticated.');if(!isSchedule())throw new Error('Open Crew Scheduler first.');const trace=loadJson(TRACE_KEY,{});if(!trace.at||Date.now()-Number(trace.at)>TRACE_MAX_AGE)throw new Error('Arm HUMAN CLICK TRACE and manually open this person first. The trace is required before assisted preparation.');if(!trace.pathText?.toLowerCase().includes(st.person.toLowerCase()))throw new Error(`The last human click trace does not show ${st.person}. Nothing changed.`);acquireLock();await diagnostic('checkpoint','precheck','Assisted preparation started; direct Save remains disabled.');await waitQuiescent(20000);const{dlg,form}=expectedModal(st.date);const before={shiftId:form.querySelector('input[name="shift_id"]')?.value||'',shiftUsersId:form.querySelector('input[name="shift_users_id"]')?.value||'',workType:dlg.querySelector('#work_type_id')?.value||''};await diagnostic('checkpoint','modal_verified','Exact Truck 504/date modal verified.',{before});const wt=dlg.querySelector('#work_type_id');if(!wt)throw new Error('Work Type field not found. Nothing changed.');await stableOptions(wt);const wtOpt=optionByValueOrText(wt,role.workType,/Salary Step\s*\[1010\]/i);if(!wtOpt)throw new Error('Salary Step [1010] is unavailable. Nothing changed.');if(String(wt.value)!==String(wtOpt.value)){await pageSetSelect(wt,[String(wtOpt.value)]);await waitQuiescent();}
 const subtype=dlg.querySelector('#work_subtype_id');if(subtype){await stableOptions(subtype);await pageSetSelect(subtype,role.subtype);await waitQuiescent();}
 const qual=findQualSelect(dlg);await stableOptions(qual);const qOpt=optionByValueOrText(qual,'',role.qualText);if(!qOpt)throw new Error(`${role.label} qualifier is unavailable. Nothing changed.`);await pageSetSelect(qual,[String(qOpt.value)]);await verifyRendered(qual,[role.qualText]);
 const labels=findLabelSelect(dlg);await stableOptions(labels);if(role.badgeText){const lOpt=optionByValueOrText(labels,'',role.badgeText);if(!lOpt)throw new Error(`${role.label} label is unavailable. Nothing changed.`);await pageSetSelect(labels,[String(lOpt.value)]);await verifyRendered(labels,[role.badgeText]);}else{await pageSetSelect(labels,[]);await waitQuiescent();}
 const still=expectedModal(st.date);if(still.form!==form)throw new Error('CrewSense replaced the assignment form during preparation. Do not save.');const qSelected=selectedTexts(qual),subSelected=subtype?selectedTexts(subtype):[],labelSelected=selectedTexts(labels);const summary={person:st.person,role:role.label,date:st.date,shiftId:before.shiftId,shiftUsersId:before.shiftUsersId,qualifiers:qSelected,subtypes:subSelected,labels:labelSelected};await diagnostic('checkpoint','pre_save_ready','ASSISTED READY: fields prepared; Scout intentionally did not click Save.',{summary});setStatus(`READY FOR MANUAL SAVE: ${st.person} → ${role.label}. Inspect CrewSense fields. Scout DID NOT click Save. If correct, you click Save yourself; if not, close the window and press CANCEL / RELEASE LOCK.`,'success');const save=[...dlg.querySelectorAll('button,a,input[type="submit"]')].find(el=>/^save$/i.test(clean(el.textContent||el.value||'')));if(save){save.style.outline='4px solid #f59e0b';save.style.outlineOffset='3px';save.dataset.rebelScoutAssistedReady='1';}
}
async function openDate(){const st=state(),hash=targetHash(st.date);const sync=loadJson('mvciServerDrivenSync_v0290',{}),lock=loadJson(LOCK_KEY,{});if(sync.active===true||(Number(lock.expiresAt||0)>Date.now()&&lock.tabId!==LOCK_OWNER)){setStatus('STOPPED: data sync or another owner lock is active. Do not navigate until it finishes.','error');return}releaseLock();if(!isSchedule()||renderedDate()!==st.date||location.hash!==hash){setStatus(`Opening ${st.date}. Wait until CrewSense's visible heading matches before arming trace.`,'info');location.assign(scheduleUrl(st.date));return}setStatus(`Crew Scheduler's displayed date and URL both match ${st.date}. You can arm the trace.`,'success')}
function traceClick(ev){
 const st=state();if(!st.armed)return;
 if(ev.target?.closest?.(`#${PANEL_ID},#${ROOT_ID}`))return;
 const row=ev.target?.closest?.('.fc-event-user[data-shift-user-id][data-user-id][data-date]');
 const group=row?.closest?.('.fc-event-shift[data-id][data-date]');
 const name=clean(row?.querySelector?.('.fc-event-user-name')?.textContent||'');
 const unitText=clean(group?.textContent||'');
 const exact=!!row&&!!group&&name===st.person&&row.dataset.date===st.date&&group.dataset.date===st.date&&
  /^Truck\s*504\b/i.test(unitText)&&/^\d+$/.test(row.dataset.userId||'')&&
  /^\d+$/.test(row.dataset.shiftUserId||'')&&/^\d+$/.test(group.dataset.id||'')&&
  isSchedule()&&renderedDate()===st.date&&location.hash===targetHash(st.date);
 if(!exact){saveState({armed:false});setStatus('TRACE STOPPED: click did not match the exact person, Truck 504, date and page. Scout did not change fields. Do not Save.','error');return}
 const path=ev.composedPath?.()||[],summary=pathSummary(path),pathText=summary.map(x=>x.text).join(' | ');
 const target={personName:name,date:st.date,unit:'Truck 504',userId:row.dataset.userId,
  shiftUserId:row.dataset.shiftUserId,assignmentId:group.dataset.id,
  qualifierId:row.dataset.qualifierid||'',rowText:clean(row.textContent||''),observedRole:clean(row.textContent||'').replace(name,'').trim()};
 const record={at:Date.now(),eventType:ev.type,x:ev.clientX,y:ev.clientY,path:summary,pathText,
  jquery:jQueryHandlers(path),date:st.date,person:st.person,role:st.role,url:location.href,target,tracePatch:TRACE_PATCH};
 saveJson(TRACE_KEY,record);saveState({armed:false});
 setStatus(`TRACE CAPTURED: ${name}, ${target.unit}, ${st.date}. Trace-only: close CrewSense modal and press CANCEL / RELEASE LOCK. Do NOT Prepare or Save.`,'success');
 diagnostic('interaction','human_click_trace','Captured exact person/date/apparatus human click; trace-only.',{humanTrace:record}).catch(()=>{});
 setTimeout(()=>diagnostic('checkpoint','human_click_after_1200ms','State 1.2s after human click.').catch(()=>{}),1200);
 setTimeout(()=>diagnostic('checkpoint','human_click_after_3000ms','State 3s after human click.').catch(()=>{}),3000)
}
document.addEventListener('pointerdown',traceClick,true);
function armTrace(){const st=state();let hash='';try{hash=targetHash(st.date)}catch(_){setStatus('STOPPED: select a valid test date first.','error');return}const sync=loadJson('mvciServerDrivenSync_v0290',{}),lock=loadJson(LOCK_KEY,{});if(sync.active===true||(Number(lock.expiresAt||0)>Date.now()&&lock.tabId!==LOCK_OWNER)){setStatus('STOPPED: sync or another owner lock is active. Trace not armed.','error');return}if(isLogin()||!isSchedule()||renderedDate()!==st.date||location.hash!==hash){setStatus('STOPPED: Crew Scheduler URL and displayed date must match the selected test date. No trace armed.','error');return}removeKey(TRACE_KEY);saveState({armed:true});setStatus(`TRACE ARMED for ${st.person} on ${st.date}. Click only the exact person row on Truck 504. No Prepare or Save.`,'info')}
function cancel(){saveState({armed:false});releaseLock();setStatus('Assisted input cancelled. Collection lock released. No Save was clicked by Scout.','info');diagnostic('checkpoint','assisted_cancelled','Assisted input cancelled / lock released.').catch(()=>{})}
function killSwitch(){cancel();document.documentElement.dataset.mvciWriterKillSwitch='1';setStatus('WRITER KILL SWITCH ON. Assisted preparation is disabled until this page is reloaded. Collectors remain available.','error')}
function ensureUi(){const root=document.getElementById(ROOT_ID),body=root?.querySelector('.body');if(!body||document.getElementById(PANEL_ID))return;const st=state(),box=document.createElement('div');box.id=PANEL_ID;box.style.cssText='margin-top:10px;padding-top:10px;border-top:1px solid #c8d3d8;font:11px Arial;color:#334b57';box.innerHTML=`<div style="font-weight:900;color:#7c4a10;margin-bottom:5px">ASSISTED INPUT LAB · ${VERSION}</div><div style="padding:7px;border:1px solid #e3bf72;background:#fff8e8;border-radius:6px;margin-bottom:7px"><b>NO AUTOMATED SAVE.</b> TRACE-ONLY MODE: capture an exact human click, close the modal and release the lock. Do not Prepare or Save.</div><label style="font-weight:700">Test date</label><input id="rs0300-date" type="date" value="${esc(st.date||'2026-09-23')}" style="width:100%;height:32px;margin:3px 0 6px"><button id="rs0300-open" type="button" style="width:100%;min-height:34px">OPEN DATE (VERIFY HEADING)</button><div style="display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:7px"><select id="rs0300-person"><option>Michael Baldree</option><option>Michael Brion</option><option>Jared Weston</option><option ${st.person==='Jerry Weems'?'selected':''}>Jerry Weems</option><option>Robert Brooks</option></select><select id="rs0300-role"><option value="TM" ${st.role==='TM'?'selected':''}>Tiller</option><option value="FFB">Firefighter</option><option value="SWING">FF / Swing</option><option value="TADE">TADE</option><option value="TAC">TAC</option></select></div><button id="rs0300-trace" type="button" style="width:100%;min-height:36px;margin-top:6px;background:#334155;color:#fff;border:0;border-radius:6px;font-weight:800">ARM HUMAN CLICK TRACE</button><button id="rs0300-prepare" type="button" style="width:100%;min-height:40px;margin-top:6px;background:#0d7895;color:#fff;border:0;border-radius:6px;font-weight:900">PREPARE DISABLED - TRACE ONLY</button><div style="display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:6px"><button id="rs0300-cancel" type="button">CANCEL / RELEASE LOCK</button><button id="rs0300-kill" type="button" style="color:#9b1c1c;font-weight:800">KILL WRITER</button></div><div id="rs0300-status" style="margin-top:7px;padding:7px;border:1px solid #d5dfe3;border-radius:6px;background:#fff;line-height:1.35">TRACE-ONLY: verify the visible date, arm trace, click the exact person, close the modal, then CANCEL / RELEASE LOCK. Never Prepare or Save.</div>`;body.appendChild(box);const date=box.querySelector('#rs0300-date'),person=box.querySelector('#rs0300-person'),role=box.querySelector('#rs0300-role');date.value=st.date||'2026-09-23';person.value=st.person||'Jerry Weems';role.value=st.role||'TM';[date,person,role].forEach(el=>el.addEventListener('change',()=>saveState({date:date.value,person:person.value,role:role.value})));
 box.querySelector('#rs0300-open').addEventListener('click',()=>{saveState({date:date.value,person:person.value,role:role.value});openDate().catch(e=>setStatus(`STOPPED: ${clean(e?.message||e)}`,'error'))});
 box.querySelector('#rs0300-trace').addEventListener('click',()=>{saveState({date:date.value,person:person.value,role:role.value});armTrace()});
 box.querySelector('#rs0300-prepare').disabled=true;box.querySelector('#rs0300-prepare').title='Not authorized in trace-only mode';
 box.querySelector('#rs0300-prepare').addEventListener('click',()=>{if(document.documentElement.dataset.mvciWriterKillSwitch==='1'){setStatus('STOPPED: writer kill switch is on. Reload the page to reset it.','error');return}saveState({date:date.value,person:person.value,role:role.value});prepareOpenAssignment().catch(async e=>{setStatus(`STOPPED: ${clean(e?.message||e)}`,'error');await diagnostic('error','assisted_abort',clean(e?.message||e));releaseLock()})});
 box.querySelector('#rs0300-cancel').addEventListener('click',cancel);box.querySelector('#rs0300-kill').addEventListener('click',killSwitch)}
function disableLegacy(){for(const id of['rebel-scout-live-test-0294','rebel-scout-live-test-0296']){const el=document.getElementById(id);if(el)el.remove()}document.querySelectorAll('#rs-schedule-save,#rs296-save,#rs-ot-sign,#rs-ot-unsign,#rs296-sign,#rs296-unsign').forEach(b=>{b.disabled=true;b.title='Retired: use Rebel Scout assisted input lab.'})}
function publish(){document.documentElement.dataset.mvciRuntimeVersion=VERSION;document.documentElement.dataset.mvciAssistedVersion=VERSION;try{window.__mvciLiveLoader.runtimeVersion=VERSION}catch(_){};document.querySelectorAll('*').forEach(el=>{if(el.children.length===0&&/^Rebel Scout\s+0\.29\.\d+-dev$/i.test(clean(el.textContent)))el.textContent=`Rebel Scout ${VERSION}`})}
function boot(){document.documentElement.dataset.mvciTracePatch=TRACE_PATCH;publish();disableLegacy();ensureUi();if(isLogin())setStatus('CrewSense session/login page detected. No assisted input is allowed.','error');diagnostic('checkpoint','module_loaded','Assisted-only writer module loaded; direct Save automation retired.').catch(()=>{})}
boot();new MutationObserver(()=>{publish();disableLegacy();ensureUi()}).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('beforeunload',()=>releaseLock());
window.REBEL_SCOUT_ASSISTED_0300={version:VERSION,armTrace,prepareOpenAssignment,cancel,diagnostic,status:()=>({state:state(),trace:loadJson(TRACE_KEY,{}),pendingNetwork:pendingNet,lock:loadJson(LOCK_KEY,{})})};
})();