(function(){
'use strict';
const VERSION='0.29.3-dev';
const ROOT_ID='mvci-command-center-v0290';
const PAIR_KEY='vectorStaffingCollectorPairing_v1';
const DEFAULT_ENDPOINT='https://base44.app/api/apps/6aa6b7634a031657377d4fad/functions/telemetryBridge';
const LOADER_URL='https://raw.githubusercontent.com/michaelbartbrion-cmd/mission-vector-check-it/feature/vector-scheduling-mvp/scheduling/vector-scheduling-loader.user.js';
if(window.top!==window.self||window.MVCI_REBEL_SCOUT_FIX_0293)return;
window.MVCI_REBEL_SCOUT_FIX_0293={version:VERSION};
const clean=v=>String(v==null?'':v).replace(/\s+/g,' ').trim();
function pairing(){try{const p=JSON.parse(localStorage.getItem(PAIR_KEY)||'{}');return{deviceId:clean(p.deviceId),token:clean(p.token),endpoint:clean(p.endpoint)||DEFAULT_ENDPOINT}}catch(_){return{deviceId:'',token:'',endpoint:DEFAULT_ENDPOINT}}}
async function request(path=''){const p=pairing();if(!p.deviceId||!p.token)throw new Error('Rebel Scout is not paired with Rebel Command.');const r=await fetch(`${p.endpoint}${path}`,{method:'GET',cache:'no-store',credentials:'omit',headers:{Authorization:`Bearer ${p.token}`,'X-Rebel-Device-ID':p.deviceId}});const b=await r.json().catch(()=>({}));if(!r.ok||b?.ok===false)throw new Error(clean(b?.error||`Rebel Command request failed (${r.status})`));return b}
function notify(message,kind='info'){const api=window.MVCI_COMMAND_CENTER_0290;if(api?.notify)api.notify(message,kind);else alert(message)}
function relabel(){const root=document.getElementById(ROOT_ID);if(!root)return;root.style.pointerEvents='auto';root.querySelectorAll('button,.panel,.body,.head,.foot,.grid').forEach(el=>{el.style.pointerEvents='auto'});const title=root.querySelector('.title');if(title){title.childNodes.forEach(n=>{if(n.nodeType===Node.TEXT_NODE&&/Mission Vector|Rebel Command|Rebel Scout/i.test(n.nodeValue||''))n.nodeValue=(n.nodeValue||'').replace(/Mission Vector|Rebel Command|Rebel Scout/gi,'Rebel Scout')})}const sub=root.querySelector('.sub');if(sub)sub.textContent='CrewSense bridge for Rebel Command';const user=root.querySelector('.user span');if(user&&/Rebel Command|Mission Vector|Rebel Scout/i.test(user.textContent||''))user.textContent='Rebel Scout · Scheduling / OT';const orb=root.querySelector('#mvci29-orb');if(orb)orb.title='Rebel Scout';}
async function startAction(type){try{const b=await request('?action=action-worklist'),rows=Array.isArray(b?.packages)?b.packages:[],matches=rows.filter(x=>x.actionType===type).sort((a,b)=>{if(a.stage==='reread_verification'&&b.stage!=='reread_verification')return-1;if(b.stage==='reread_verification'&&a.stage!=='reread_verification')return 1;return String(a.targetDate||'').localeCompare(String(b.targetDate||''))});if(!matches.length)throw new Error(type==='schedule'?'No approved riding-plan changes are waiting in Rebel Command Scheduling.':'No approved OT signup actions are waiting in Rebel Command Overtime.');const runner=window.MVCI_ACTION_RUNNER_0290;if(!runner?.startInput)throw new Error('Rebel Scout action runner is not available. Reload CrewSense and try again.');runner.startInput(type,matches[0].targetDate)}catch(e){notify(clean(e?.message||e),'error')}}
async function configure(){try{const bridge=window.MVCI_VECTOR_BRIDGE_0290;if(!bridge?.configure)throw new Error('Rebel Scout connection tool is not available. Reload CrewSense and try again.');await bridge.configure();await request('');notify('Rebel Scout connection verified with Rebel Command.','success')}catch(e){notify(`Connection failed: ${clean(e?.message||e)}`,'error')}}
async function update(){try{if(typeof window.MVCI_SCHEDULER_CHECK_UPDATE==='function'){await window.MVCI_SCHEDULER_CHECK_UPDATE();return}window.open(LOADER_URL,'_blank','noopener');notify('Opened the Rebel Scout loader because the in-page update hook was unavailable.','info')}catch(e){notify(`Update check failed: ${clean(e?.message||e)}`,'error')}}
function handle(ev){const root=document.getElementById(ROOT_ID);if(!root)return;const btn=ev.target?.closest?.('button');if(!btn||!root.contains(btn))return;const id=btn.id;if(!['mvci29-sync','mvci29-stop','mvci29-ride','mvci29-ot','mvci29-update','mvci29-connect'].includes(id))return;ev.preventDefault();ev.stopImmediatePropagation();if(id==='mvci29-sync'){const q=window.MVCI_COMMAND_CENTER_0290?.status?.()?.queue;if(q?.active)window.MVCI_COMMAND_CENTER_0290?.runQueue?.();else window.MVCI_COMMAND_CENTER_0290?.startSync?.(false);return}if(id==='mvci29-stop'){window.MVCI_COMMAND_CENTER_0290?.stopSync?.('Data sync stopped by user.');return}if(id==='mvci29-ride'){startAction('schedule');return}if(id==='mvci29-ot'){startAction('overtime_signup');return}if(id==='mvci29-update'){update();return}if(id==='mvci29-connect'){configure();return}}
document.addEventListener('click',handle,true);
relabel();
new MutationObserver(()=>relabel()).observe(document.documentElement,{childList:true,subtree:true});
try{document.documentElement.dataset.mvciRuntimeVersion=VERSION}catch(_){}
})();
