(function(){
'use strict';
const VERSION='0.29.0-dev';
const ENDPOINT='https://base44.app/api/apps/6aa6b7634a031657377d4fad/functions/telemetryBridge';
const PAIR_KEY='vectorStaffingCollectorPairing_v1';
const STABLE_MS=900;
const MIN_ROWS=24;
const MIN_REGULAR=20;
const MIN_GROUPS=6;
if(window.top!==window.self||window.MVCI_VECTOR_BRIDGE_0290)return;

const state={lastMutationAt:Date.now(),running:false,currentPromise:null,status:'idle',lastCapture:null,lastError:''};
const clean=v=>String(v==null?'':v).replace(/\s+/g,' ').trim();
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function loadJson(k,f={}){try{const r=localStorage.getItem(k);return r?JSON.parse(r):f}catch(_){return f}}
function saveJson(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}}
function pairing(){const p=loadJson(PAIR_KEY,{});return{deviceId:clean(p.deviceId),token:clean(p.token),endpoint:clean(p.endpoint)||ENDPOINT}}
function paired(){const p=pairing();return!!(p.deviceId&&p.token)}
function parseDate(value){const t=clean(value);let m=t.match(/\b(20\d{2})[-/](\d{1,2})[-/](\d{1,2})\b/);if(m)return`${m[1]}-${String(+m[2]).padStart(2,'0')}-${String(+m[3]).padStart(2,'0')}`;m=t.match(/\b(\d{1,2})[/-](\d{1,2})[/-](20\d{2})\b/);if(m)return`${m[3]}-${String(+m[1]).padStart(2,'0')}-${String(+m[2]).padStart(2,'0')}`;const months={jan:1,january:1,feb:2,february:2,mar:3,march:3,apr:4,april:4,may:5,jun:6,june:6,jul:7,july:7,aug:8,august:8,sep:9,sept:9,september:9,oct:10,october:10,nov:11,november:11,dec:12,december:12};m=t.match(/\b(?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)?\s*,?\s*(January|February|March|April|May|June|July|August|September|October|November|December|Jan|Feb|Mar|Apr|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec)\s+(\d{1,2}),\s*(20\d{2})\b/i);return m?`${m[3]}-${String(months[m[1].toLowerCase()]).padStart(2,'0')}-${String(+m[2]).padStart(2,'0')}`:''}
function rendered(el){if(!el||!(el instanceof Element))return false;const s=getComputedStyle(el);if(s.display==='none'||s.visibility==='hidden')return false;const r=el.getBoundingClientRect();return r.width>0&&r.height>0}
function ownElement(el){return!!el?.closest?.('[id^="mvci-"],#mvci-vs-panel,#mvci-vs-open,[id^="vs-"],#vector-staffing-collector-status,#vector-overtime-collector-status')}
function domDisplayedDate(){
  const reader=window.MVCI_VECTOR_READER_0120;
  const rd=clean(reader?.visibleDisplayedDate?.()||'');
  if(/^\d{4}-\d{2}-\d{2}$/.test(rd))return rd;
  const candidates=[];
  for(const el of document.querySelectorAll('h1,h2,h3,time,input[type="date"],[data-date],[datetime],[class*="date"],[id*="date"],span,div')){
    if(ownElement(el)||!rendered(el))continue;
    const values=[el.value,el.getAttribute?.('data-date'),el.getAttribute?.('datetime'),el.textContent];
    for(const v of values){if(!v||clean(v).length>120)continue;const d=parseDate(v);if(!d)continue;let score=0;const tag=(el.tagName||'').toLowerCase();if(/^h[1-3]$/.test(tag))score+=10;if(tag==='time')score+=8;if(el.matches?.('input[type="date"],[data-date],[datetime]'))score+=7;const cls=clean(el.className||'').toLowerCase();if(/date|day/.test(cls))score+=4;candidates.push({d,score})}
  }
  candidates.sort((a,b)=>b.score-a.score);return candidates[0]?.d||'';
}
function loadingVisible(){return[...document.querySelectorAll('[aria-busy="true"],.loading,.spinner,[class*="loading"],[class*="spinner"]')].some(el=>rendered(el)&&!ownElement(el))}
function rowMarker(t){return/Salary Step\s*\[1010\]|\bSub\s*\[1010\]|Additional Time|Disaster Relief|Overtime|OT Sign|Force Hire|Backfill|Trade|Swap|Open Slot|Vacation|Sick|Leave|Time Off/i.test(t)}
function looksLikeScheduleRow(t){t=clean(t);return/\b\d{1,2}:\d{2}\s*-\s*\d{1,2}:\d{2}\b/.test(t)&&(rowMarker(t)||/^Open Slot\b/i.test(t))}
function candidateElements(root=document){const pool=[...root.querySelectorAll('tr,[role="row"],li,article,section,div')].filter(el=>rendered(el)&&!ownElement(el)).map(el=>({el,text:clean(el.textContent)})).filter(x=>x.text.length>=8&&x.text.length<=900&&looksLikeScheduleRow(x.text));const selected=[];for(const item of pool.sort((a,b)=>a.text.length-b.text.length)){if(selected.some(x=>item.el.contains(x.el)))continue;selected.push(item)}return selected}
const GROUP_RE=/\b(Engine|Truck|Medic|Quint|Rescue|Battalion|Brush|Squad|Tower|Ladder|Ambulance|Station)\s+\d{1,4}\b/i;
function groupFor(el){let n=el;for(let d=0;n&&d<10;d++,n=n.parentElement){if(ownElement(n))continue;const text=clean(n.textContent).slice(0,5000),m=[...text.matchAll(new RegExp(GROUP_RE.source,'ig'))];if(m.length===1)return clean(m[0][0]);if(m.length>1&&d<=2)return clean(m[m.length-1][0])}let p=el.previousElementSibling;for(let i=0;p&&i<8;i++,p=p.previousElementSibling){const m=clean(p.textContent).match(GROUP_RE);if(m)return clean(m[0])}return''}
function hoursFrom(t){t=clean(t);let m=t.match(/\b(\d+(?:\.\d+)?)\s*(?:hrs?|hours?)(?:\s+(\d+)\s*min)?\b/i);if(m)return Math.round((+m[1]+ +(m[2]||0)/60)*100)/100;m=t.match(/\b(\d{1,2}):(\d{2})\s*-\s*(\d{1,2}):(\d{2})\b/);if(!m)return null;let a=+m[1]+ +m[2]/60,b=+m[3]+ +m[4]/60;if(b<=a)b+=24;return Math.round((b-a)*100)/100}
function scheduleType(t){t=clean(t);for(const re of[/Salary Step\s*\[1010\](?:\s*-\s*[^\[]+\[[^\]]+\])?/i,/\bSub\s*\[1010\]/i,/Additional Time[^\[]*(?:\[[^\]]+\])?/i,/Salary Disaster Relief[^\[]*(?:\[[^\]]+\])?/i,/Overtime[^\[]*(?:\[[^\]]+\])?/i]){const m=t.match(re);if(m)return clean(m[0])}return''}
function personAndDuty(t){t=clean(t);if(/^Open Slot\b/i.test(t))return{personName:'Open Slot',dutyCode:''};const marker=t.search(/\s+(?=Salary Step\s*\[1010\]|Sub\s*\[1010\]|Additional Time|Salary Disaster Relief|Overtime|OT Sign|Force Hire|Backfill|Trade|Swap|Vacation|Sick|Leave|Time Off)/i),prefix=clean(marker>0?t.slice(0,marker):t),tokens=prefix.split(' ').filter(Boolean),status=new Set(['S','A','O','V']),duties=new Set(['CAPT','CAPTAIN','BC','CHIEF','DE','DE-A','DE-B','DE-C','FF','FFA','FFB','FFC','TM','TILLER','TADE','TAC','SWING','FTO']);while(tokens.length&&status.has(tokens[tokens.length-1].toUpperCase()))tokens.pop();while(tokens.length&&tokens[tokens.length-1]==='-')tokens.pop();const out=[];while(tokens.length&&duties.has(tokens[tokens.length-1].toUpperCase()))out.unshift(tokens.pop());while(tokens.length&&tokens[tokens.length-1]==='-')tokens.pop();if(tokens.length>2&&/^\d+$/.test(tokens[tokens.length-1]))tokens.pop();return{personName:clean(tokens.join(' ')).slice(0,180),dutyCode:clean(out.join(' '))}}
function hash32(t){let h=0x811c9dc5;for(let i=0;i<t.length;i++){h^=t.charCodeAt(i);h=Math.imul(h,0x01000193)}return(h>>>0).toString(36)}
function makeRow(item){const rawText=clean(item.text),group=groupFor(item.el),pd=personAndDuty(rawText),lengthHours=hoursFrom(rawText);return{personId:`dom-${hash32((pd.personName||rawText).toLowerCase())}`,personName:pd.personName,activity:'Work Shift',assignment:group,assignmentGroup:group,dutyCode:pd.dutyCode,scheduleType:scheduleType(rawText),...(Number.isFinite(lengthHours)?{lengthHours}:{}),captureQuality:group?'row+group':'row-only',rawText}}
function findScroller(el){let n=el?.parentElement||null;for(let d=0;n&&d<12;d++,n=n.parentElement){const s=getComputedStyle(n);if(n.scrollHeight>n.clientHeight+80&&/(auto|scroll)/i.test(s.overflowY||''))return n}return null}
function merge(target,items){for(const item of items){const r=makeRow(item);if(!r.personName||!r.rawText)continue;const k=`${r.assignmentGroup}|${r.rawText}`;if(!target.has(k))target.set(k,r)}}
async function sweep(){const found=new Map(),initial=candidateElements();merge(found,initial);const scroller=findScroller(initial[0]?.el);if(!scroller)return{rows:[...found.values()],scrollSweepComplete:true,scroller:'none'};const original=scroller.scrollTop,max=Math.max(0,scroller.scrollHeight-scroller.clientHeight),step=Math.max(180,Math.floor(scroller.clientHeight*.7));let bottom=false;try{for(let pos=0,loops=0;pos<=max+step&&loops<120;pos+=step,loops++){scroller.scrollTop=Math.min(pos,max);await wait(document.hidden?180:90);merge(found,candidateElements(scroller));if(scroller.scrollTop>=max-3){bottom=true;merge(found,candidateElements(scroller));break}}}finally{scroller.scrollTop=original;await wait(160)}return{rows:[...found.values()],scrollSweepComplete:bottom,scroller:'element'}}
async function waitStable(max=10000){const start=Date.now();while(Date.now()-start<max){if(Date.now()-state.lastMutationAt>=STABLE_MS&&!loadingVisible())return true;await wait(document.hidden?250:100)}return false}
async function verifyPair(p){const r=await fetch(p.endpoint||ENDPOINT,{method:'GET',cache:'no-store',credentials:'omit',headers:{Authorization:`Bearer ${p.token}`,'X-Rebel-Device-ID':p.deviceId}});if(!r.ok)throw new Error(`Pairing rejected (${r.status})`);return r.json().catch(()=>({}))}
async function configure(){const cur=pairing();if(cur.deviceId&&cur.token){const a=prompt('Mission Vector is paired. Type TEST to test, REPAIR to replace credentials, CLEAR to remove pairing, or leave blank to cancel.','TEST');if(!a)return;const u=a.trim().toUpperCase();if(u==='TEST'){try{await verifyPair(cur);alert('Rebel Command pairing is working.')}catch(e){alert(`Pairing test failed: ${e.message||e}`)}return}if(u==='CLEAR'){localStorage.removeItem(PAIR_KEY);return}if(u!=='REPAIR')return}const deviceId=clean(prompt('Paste the Rebel Command Device ID:',cur.deviceId||'')||'');if(!deviceId)return;const token=clean(prompt('Paste the private device token from Rebel Command:','')||'');if(!token)return;const next={deviceId,token,endpoint:ENDPOINT};await verifyPair(next);saveJson(PAIR_KEY,next);alert('Mission Vector paired with Rebel Command.')}
async function sendCapture(payload){const p=pairing();if(!p.deviceId||!p.token)throw new Error('Pair Rebel Command first.');const r=await fetch(p.endpoint||ENDPOINT,{method:'POST',cache:'no-store',credentials:'omit',headers:{Authorization:`Bearer ${p.token}`,'X-Rebel-Device-ID':p.deviceId,'Content-Type':'application/json'},body:JSON.stringify({version:VERSION,staffingCapture:payload})});const b=await r.json().catch(()=>({}));if(!r.ok||b?.ok===false)throw new Error(b?.error||`Rebel Command rejected capture (${r.status})`);return b}
async function performScrape(options={}){state.running=true;state.status='reading';state.lastError='';const expected=clean(options.expectedDate||'');try{const stableBefore=await waitStable();const before=domDisplayedDate();if(!before)throw new Error('Could not identify the rendered ListView date.');if(expected&&before!==expected)throw new Error(`CrewSense rendered ${before}, not requested ${expected}.`);const result=await sweep();const stableAfter=await waitStable(6000);const after=domDisplayedDate();if(!after||before!==after)throw new Error(`Rendered date changed during scrape (${before||'unknown'} → ${after||'unknown'}).`);if(expected&&after!==expected)throw new Error(`CrewSense rendered ${after}, not requested ${expected}.`);const rows=result.rows,regular=rows.filter(r=>/Salary Step\s*\[1010\]/i.test(r.scheduleType||r.rawText)&&Number(r.lengthHours)===24&&!/Sub\s*\[1010\]|Additional Time|Overtime|OT Sign|Force Hire|Backfill|Disaster Relief|Trade|Swap|Vacation|Sick|Leave|Time Off/i.test(r.rawText)).length,groups=new Set(rows.map(r=>r.assignmentGroup).filter(Boolean)).size,noLoading=!loadingVisible(),full=stableBefore&&stableAfter&&noLoading&&result.scrollSweepComplete&&rows.length>=MIN_ROWS&&regular>=MIN_REGULAR&&groups>=MIN_GROUPS,digest=hash32(JSON.stringify(rows.map(r=>[r.personId,r.assignmentGroup,r.rawText]).sort())),capturedAt=new Date().toISOString(),payload={batchId:`unified:${before}:${Date.now()}:${digest}`,capturedAt,sourceVersion:`vector-bridge-${VERSION}`,pageMode:'ListView',captureComplete:full,diagnostics:{pageStableBefore:stableBefore,pageStableAfter:stableAfter,pageStable:stableBefore&&stableAfter,allVisibleGroupsScanned:result.scrollSweepComplete,scrollSweepComplete:result.scrollSweepComplete,noLoadingIndicator:noLoading,dateConfidence:'high',dateSource:'rendered-dom',expectedDate:expected||null,visibleScheduleRows:rows.length,candidateRegularRows:regular,groupCount:groups,scroller:result.scroller},days:[{workDate:before,shiftLabel:'',rows}]};const body=await sendCapture(payload);state.status=body?.staffing?.quality==='good'?'sent-good':'sent-partial';state.lastCapture={date:before,rows:rows.length,regular,groups,full,quality:body?.staffing?.quality||'unknown',at:capturedAt,sourceVersion:`vector-bridge-${VERSION}`};return status()}catch(e){state.status='error';state.lastError=clean(e?.message||e);throw e}finally{state.running=false;state.currentPromise=null}}
function scrapeNow(options={}){if(state.currentPromise)return state.currentPromise;state.currentPromise=performScrape(options);return state.currentPromise}
function status(){return{paired:paired(),running:state.running,status:state.status,lastCapture:state.lastCapture,lastError:state.lastError,renderedDate:domDisplayedDate(),version:VERSION}}
function mutationRelevant(m){const target=m.target?.nodeType===1?m.target:m.target?.parentElement;if(target&&ownElement(target))return false;if(m.type==='childList'){const nodes=[...m.addedNodes,...m.removedNodes];if(nodes.length&&nodes.every(n=>{const el=n.nodeType===1?n:n.parentElement;return el?ownElement(el):false}))return false}return true}
const observer=new MutationObserver(ms=>{if(ms.some(mutationRelevant))state.lastMutationAt=Date.now()});observer.observe(document.documentElement,{childList:true,subtree:true,characterData:true});
window.MVCI_VECTOR_BRIDGE_0290={version:VERSION,configure,scrapeNow,status,renderedDate:domDisplayedDate};
})();