(function(){
'use strict';
const VERSION='0.12.0-dev';
const KEY='missionVectorScheduling_v3';
const Engine=window.VectorSchedulingEngine;
if(window.top!==window.self||window.__mvciVectorBootstrap0120)return;
window.__mvciVectorBootstrap0120={version:VERSION,startedAt:Date.now()};
if(!Engine){console.error('Vector Scheduling: rotation engine missing.');return;}
const clean=v=>String(v==null?'':v).replace(/\s+/g,' ').trim();
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=(...p)=>p.map(v=>clean(v).toLowerCase()).join('|');
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
function defaults(){return{schemaVersion:3,settings:{apparatusName:'Truck 504',firefighters:[],command:[],balanceStartDate:null,balanceEndDate:null,blockDays:2,horizonBlocks:12,shiftLengthHours:24,scenarioDefault:'auto',autoCaptureOnSchedulePages:true},history:[],dutyHistory:[],plans:[],observations:[],reviews:[],resolutions:[],segments:[],metadata:{createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),runtimeVersion:VERSION}};}
function normalize(raw){const d=defaults(),x=raw&&typeof raw==='object'?raw:{};const s={...d,...x,settings:{...d.settings,...(x.settings||{})},metadata:{...d.metadata,...(x.metadata||{})}};for(const k of ['history','dutyHistory','plans','observations','reviews','resolutions','segments'])if(!Array.isArray(s[k]))s[k]=[];if(!Array.isArray(s.settings.firefighters))s.settings.firefighters=[];if(!Array.isArray(s.settings.command))s.settings.command=[];s.schemaVersion=3;return s;}
function load(){try{return normalize(JSON.parse(localStorage.getItem(KEY)||'null'));}catch(_){return normalize(null);}}
function save(s){s.metadata=s.metadata||{};s.metadata.updatedAt=new Date().toISOString();s.metadata.runtimeVersion=VERSION;localStorage.setItem(KEY,JSON.stringify(s));}
function people(s){return[...(s.settings?.firefighters||[]),...(s.settings?.command||[])];}
function ffids(s){return(s.settings?.firefighters||[]).map(p=>p.id);}
function upsert(list,row,keyFn){const k=keyFn(row),i=list.findIndex(x=>keyFn(x)===k);if(i>=0)list[i]=row;else list.push(row);}
function mergeImport(s,p){if(!p||typeof p!=='object')throw new Error('Invalid JSON file.');if(p.settings)s.settings={...s.settings,...p.settings};const keys={history:x=>uid(x.date,x.personId,x.credit,x.detail),dutyHistory:x=>uid(x.date,x.personId,x.detail,x.source),plans:x=>uid(x.date,x.personId),observations:x=>uid(x.date,x.personId,x.capturedAt,x.source),reviews:x=>uid(x.date,x.personId,x.observationCapturedAt),resolutions:x=>uid(x.date,x.personId,x.resolvedAt),segments:x=>uid(x.date,x.personId,x.role,x.startTime,x.endTime)};for(const[k,fn]of Object.entries(keys)){s[k]=Array.isArray(s[k])?s[k]:[];for(const row of(p[k]||[]))upsert(s[k],row,fn);}if(Array.isArray(p.ratioPeriods))s.ratioPeriods=p.ratioPeriods;s.metadata=s.metadata||{};s.metadata.lastImportAt=new Date().toISOString();save(s);}
function stats(s){return Engine.statsFromHistory(s.history||[],ffids(s),s.settings?.balanceStartDate||null,s.settings?.balanceEndDate||null);}
function segHours(a,b){const A=a.split(':').map(Number),B=b.split(':').map(Number);if([...A,...B].some(x=>!Number.isFinite(x)))return null;let m=(B[0]*60+B[1])-(A[0]*60+A[1]);if(m<=0)m+=1440;return m/60;}
function addSegment(s,date,personId,role,start,end,note){const h=segHours(start,end);if(!date||!personId||!role||!h)throw new Error('Complete all partial-duty fields.');const row={date,personId,role,startTime:start,endTime:end,durationHours:h,fractionOfShift:Math.min(1,h/Number(s.settings?.shiftLengthHours||24)),countsTowardRotation:true,verified:true,source:'manual-partial-duty',note:clean(note),createdAt:new Date().toISOString()};upsert(s.segments,row,x=>uid(x.date,x.personId,x.role,x.startTime,x.endTime));save(s);return row;}
function exportState(s){const b=new Blob([JSON.stringify(s,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`vector-scheduling-private-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function css(){if(document.getElementById('mvci-vs-style'))return;const st=document.createElement('style');st.id='mvci-vs-style';st.textContent='#mvci-vs-open{position:fixed;right:18px;bottom:18px;z-index:2147483646;width:60px;height:60px;border:0;border-radius:50%;background:#17365d;color:#fff;font:700 14px Arial;cursor:pointer;box-shadow:0 3px 14px #0006}#mvci-vs-panel{position:fixed;right:0;top:0;width:min(560px,97vw);height:100vh;z-index:2147483647;background:#f7f9fc;color:#17202a;font:13px/1.4 Arial;box-shadow:-4px 0 18px #0005;overflow:auto}#mvci-vs-panel *{box-sizing:border-box}.vs-head{display:flex;gap:8px;align-items:center;background:#17365d;color:#fff;padding:12px}.vs-head strong{flex:1;font-size:16px}.vs-card{background:#fff;border:1px solid #d8e0e9;border-radius:8px;padding:10px;margin:10px}.vs-card h3{margin:0 0 8px}.vs-btn{padding:7px 10px;border:1px solid #315a88;border-radius:5px;background:#315a88;color:#fff;cursor:pointer}.vs-btn.secondary{background:#fff;color:#17365d}.vs-update{background:#f0b429;border-color:#f0b429;color:#111;font-weight:700}.vs-input,.vs-select{width:100%;padding:6px;border:1px solid #aebdce;border-radius:5px}.vs-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.vs-grid3{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.vs-table{width:100%;border-collapse:collapse;font-size:12px}.vs-table th,.vs-table td{border-bottom:1px solid #e2e7ed;padding:5px;text-align:left}.vs-muted{font-size:11px;color:#687787}';document.head.appendChild(st);}
function render(){css();let s=load();save(s);let open=document.getElementById('mvci-vs-open');if(!open){open=document.createElement('button');open.id='mvci-vs-open';open.textContent='VS';document.body.appendChild(open);}let panel=document.getElementById('mvci-vs-panel');if(!panel){panel=document.createElement('div');panel.id='mvci-vs-panel';panel.style.display='none';document.body.appendChild(panel);}const st=stats(s),ids=ffids(s),person=id=>people(s).find(p=>p.id===id)||{name:id};const opts=(s.settings.firefighters||[]).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');panel.innerHTML=`<div class="vs-head"><strong>Vector Scheduling DEV <span style="opacity:.7;font-size:11px">${VERSION}</span></strong><button class="vs-btn vs-update" id="vs-update">↻ UPDATE</button><button class="vs-btn secondary" id="vs-close">×</button></div><div class="vs-card"><h3>Confirmed full-shift rotation</h3>${ids.length?`<table class="vs-table"><tr><th>Firefighter</th>${Engine.CREDIT_CATEGORIES.map(c=>`<th>${c}</th>`).join('')}<th>Total</th></tr>${ids.map(id=>`<tr><td><strong>${esc(person(id).name)}</strong></td>${Engine.CREDIT_CATEGORIES.map(c=>`<td>${(((st[id]?.ratios?.[c]||0)*100)).toFixed(1)}%</td>`).join('')}<td>${st[id]?.total||0}</td></tr>`).join('')}</table>`:'<div>Import the private Truck 504 JSON below.</div>'}</div><div class="vs-card"><h3>Read current Vector page</h3><button class="vs-btn" id="vs-capture">Capture displayed date</button><div class="vs-muted" style="margin-top:6px">Read-only. This records what Vector shows; it does not change Vector.</div><div class="vs-muted" style="margin-top:4px">Last capture: ${esc(s.metadata?.lastCaptureAt?new Date(s.metadata.lastCaptureAt).toLocaleString():'none')}</div></div><div class="vs-card"><h3>Partial-day duty exposure</h3><div class="vs-grid3"><div><label>Date</label><input id="seg-date" class="vs-input" type="date" value="${today()}"></div><div><label>Firefighter</label><select id="seg-person" class="vs-select">${opts}</select></div><div><label>Role</label><select id="seg-role" class="vs-select"><option>Firefighter</option><option>Swing</option><option>Tiller</option><option>TADE</option></select></div></div><div class="vs-grid3" style="margin-top:7px"><div><label>Start</label><input id="seg-start" class="vs-input" type="time" value="07:00"></div><div><label>End</label><input id="seg-end" class="vs-input" type="time" value="12:00"></div><div><label>Note</label><input id="seg-note" class="vs-input" value=""></div></div><button id="seg-save" class="vs-btn" style="margin-top:7px">Record partial duty</button><div class="vs-muted" style="margin-top:6px">Partial assignments are stored with exact duration for proportional rotation exposure.</div></div><div class="vs-card"><h3>Import / export</h3><input id="vs-import" type="file" accept="application/json,.json"><div style="margin-top:7px"><button id="vs-export" class="vs-btn secondary">Export private state JSON</button></div></div>`;
open.onclick=()=>{panel.style.display=panel.style.display==='none'?'block':'none';};panel.querySelector('#vs-close').onclick=()=>panel.style.display='none';panel.querySelector('#vs-export').onclick=()=>exportState(load());panel.querySelector('#vs-import').onchange=async e=>{try{const f=e.target.files?.[0];if(!f)return;const p=JSON.parse(await f.text());const cur=load();mergeImport(cur,p);alert('Private scheduling state imported. Reloading.');location.reload();}catch(err){alert('Import failed: '+(err.message||err));}};panel.querySelector('#seg-save').onclick=()=>{try{const cur=load();addSegment(cur,panel.querySelector('#seg-date').value,panel.querySelector('#seg-person').value,panel.querySelector('#seg-role').value,panel.querySelector('#seg-start').value,panel.querySelector('#seg-end').value,panel.querySelector('#seg-note').value);alert('Partial-duty exposure recorded.');}catch(err){alert(err.message||err);}};
}
render();
})();