'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'..','outlook-rebel-postmaster-ui.user.js'),'utf8');
assert.match(source,/@version\s+0\.3\.0/);
assert.doesNotMatch(source,/new\s+MutationObserver\s*\(|setInterval\s*\(|setTimeout\s*\(|GM_xmlhttpRequest\s*\(|fetch\s*\(/);
assert.doesNotMatch(source,/\.click\s*\(|\.submit\s*\(/);
for(const name of ['v014','v015','v016'])assert.match(source,new RegExp('mvci-work-email-reader-'+name));
assert.match(source,/readerBehaviorUnchanged:true/);
assert.match(source,/data:image\/png;base64/);
assert.match(source,/nth-of-type\(2\).*display:none/s,'upload button is visually hidden');
let injected=[],requests=0,timers=0;
const win={};win.top=win;win.self=win;
const doc={createElement:tag=>({tagName:tag.toUpperCase(),id:'',textContent:''}),documentElement:{appendChild:el=>injected.push(el)}};
const context={window:win,document:doc,fetch:()=>requests++,setInterval:()=>timers++,setTimeout:()=>timers++};
vm.runInNewContext(source,context,{timeout:1000});
assert.equal(injected.length,1,'stylesheet injected once even with no reader present');
assert.equal(injected[0].tagName,'STYLE');
assert.match(injected[0].textContent,/REBEL POSTMASTER/);
assert.match(injected[0].textContent,/PREVIEW VISIBLE MAIL/);
assert.equal(win.MVCI_POSTMASTER_BROWSER_030.presentationOnly,true);
vm.runInNewContext(source,context,{timeout:1000});
assert.equal(injected.length,1,'idempotent on duplicate execution');
assert.equal(requests,0);assert.equal(timers,0);
console.log('postmaster-browser-ui: PASS (3 reader versions, permanent CSS on redraw, actual logo, no observers/network/timers)');
