'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const source=name=>fs.readFileSync(path.join(__dirname,'..',name),'utf8');
const loader=source('vector-scheduling-loader.user.js');
let requests=0,loads=0;
const self={};const win={self,top:self};const dataset={};
const document={getElementById:()=>null,documentElement:{dataset}};
vm.runInNewContext(loader,{window:win,document,GM_xmlhttpRequest:()=>{requests++},console:{warn:()=>{},error:()=>{}},Date,setTimeout:()=>{loads++}}, {timeout:1000});
assert.equal(requests,0,'loader must not make any network requests in stability hold');
assert.equal(loads,0,'loader must not schedule script startup in stability hold');
assert.equal(win.__mvciLiveLoader?.disabled,true);
assert.equal(win.__mvciLiveLoader?.runtimeVersion,'stability-hold');
assert.equal(win.__mvciLiveLoader?.complete,false);
assert.deepEqual(Array.from(win.__mvciLiveLoader.loadedScripts),[]);
const assisted=source('rebel-scout-assisted-input-0.30.0.js');
assert.match(assisted,/const PREPARATION_ENABLED=false/);
assert.doesNotMatch(assisted,/^installPageProbe\(\);/m,'no automatic interception of CrewSense XHR/fetch');
assert.doesNotMatch(assisted,/new MutationObserver\([^\n]*\)\.observe\(document\.documentElement/,'no global Scout observer');
assert.doesNotMatch(assisted,/document\.querySelectorAll\('\*'\)/,'no full document walk');
assert.doesNotMatch(assisted,/window\.__mvciLiveLoader\.runtimeVersion\s*=\s*VERSION/,'Scout must not falsify shared loader identity');
assert.match(assisted,/scoutRootWatch\.observe\(root,\{childList:true\}\)/);
assert.match(source('rebel-scout-ui-fix-0.29.3.js'),/relabelRootWatch\.observe\(root,\{childList:true\}\)/);
for(const name of ['rebel-scout-ui-fix-0.29.3.js','rebel-command-loader-ui-patch-0.30.3.js','rebel-command-dst-ui-patch-0.29.1.js','rebel-command-write-mapper-0.29.2.js']){
 assert.doesNotMatch(source(name),/new MutationObserver\([^\n]*\)\.observe\(document\.documentElement/,'global visual observer: '+name);
}
const command=source('mission-vector-command-center-0.29.0.js');
assert.doesNotMatch(command,/setTimeout\(safeAuto/,'automatic sync prohibited at startup');
assert.doesNotMatch(command,/setTimeout\(\(\)=>\{const q=queue\(\);if\(q\.active\)runQueue\(\)\}/,'no old queue resume at startup');
assert.match(command,/async function startSync\(automatic=false\)/,'manual read-only sync code retained');
const core=source('rebel-core-scheduling-sync-0.21.0.js');
assert.doesNotMatch(core,/setInterval\(\(\)\s*=>\s*\{\s*if\s*\(paired\(\)\)\s*syncNow/,'no background ledger sends');
assert.doesNotMatch(core,/setTimeout\(\(\)\s*=>\s*\{\s*if\s*\(paired\(\)\)\s*syncNow/,'no boot ledger sends');
const backfill=source('vector-scheduling-runtime-backfill-0.13.0.js');
assert.doesNotMatch(backfill,/if\(loadRun\(\)\?\.active\)setTimeout\(runBackfill/,'old historical scan must not resume');
assert.match(backfill,/interrupted\.active=false/,'interrupted run is explicitly paused');
const dst=source('rebel-command-dst-ui-patch-0.29.1.js');
assert.doesNotMatch(dst,/window\.fetch\s*=/,'DST normalizer must never intercept global fetch');
assert.match(dst,/patchStaffingCapture=patchStaffingCapture/);
const dstSelf={};const dstWindow={top:dstSelf,self:dstSelf};
vm.runInNewContext(dst,{window:dstWindow,document:{querySelectorAll:()=>[]},console}, {timeout:1000});
const payload={staffingCapture:{sourceVersion:'vector-bridge-0.29.0-dev',days:[{rows:Array.from({length:24},(_,i)=>({scheduleType:'Salary Step [1010]',lengthHours:i<20?23:12,rawText:'Work Shift'}))}],diagnostics:{groupCount:6,pageStable:true,allVisibleGroupsScanned:true,scrollSweepComplete:true,noLoadingIndicator:true}}};
assert.equal(dstWindow.REBEL_COMMAND_DST_UI_PATCH_0291.patchStaffingCapture(payload).staffingCapture.captureComplete,true,'DST 23-hour capture adjustment must survive without fetch patching');
const staffing=source('vector-staffing-bridge-0.29.0.js');
assert.match(staffing,/function startObservation\(\)/);
assert.match(staffing,/async function performScrape\(options=\{\}\)\{state\.running=true;/);
assert.match(staffing,/try\{startObservation\(\);const stableBefore=/);
assert.match(staffing,/finally\{stopObservation\(\);state\.running=false/);
assert.match(staffing,/patchStaffingCapture\?\./);
assert.doesNotMatch(staffing,/window\.fetch\s*=/);
// With a browser body present, the stability hold displays only a dismissible,
// inert status. It must not boot any module, network request or background timer.
const made=[],body={appendChild:el=>made.push(el)};
function element(tag){return {tag,style:{},setAttribute(){},append(){},appendChild(){},addEventListener(){},remove(){},set textContent(v){this.text=v},get textContent(){return this.text}}}
let holdRequests=0,holdTimers=0;const safetyWindow={};safetyWindow.self=safetyWindow;safetyWindow.top=safetyWindow;
const safetyDoc={body,documentElement:{dataset:{}},createElement:element,getElementById:()=>null};
vm.runInNewContext(loader,{window:safetyWindow,document:safetyDoc,GM_xmlhttpRequest:()=>holdRequests++,console:{warn(){},error(){}},Date,setTimeout:()=>holdTimers++},{timeout:1000});
assert.equal(made.length,1,'one compact recovery status, no old operational panel');
assert.equal(made[0].id,'mvci-scout-recovery');
assert.equal(safetyWindow.__mvciLiveLoader.disabled,true);
assert.equal(holdRequests,0);assert.equal(holdTimers,0);
assert.equal(safetyWindow.__mvciLiveLoader.loadedScripts.length,0);
console.log('rebel-scout-incident-guards: PASS (loader no-op, no background sends, no broad UI observers, no page interception)');
